// @generated by `lark-rs generate-parser` — DO NOT EDIT.
//
// A self-contained LALR parser. Depends only on the `regex` crate and the
// Rust standard library — not on lark-rs. Drop it into any crate that has
// `regex` as a dependency and call `Parser::new().parse(text)`.
//
// Source grammar:
//   // Arithmetic grammar for testing operator precedence, unary ops, and parentheses.
//   // Mirrors what Lark's test_parser.py uses for LALR precedence tests.
//   
//   ?start : expr
//   
//   ?expr  : expr "+" term  -> add
//          | expr "-" term  -> sub
//          | term
//   
//   ?term  : term "*" factor -> mul
//          | term "/" factor -> div
//          | factor
//   
//   ?factor : "+" factor    -> pos
//           | "-" factor    -> neg
//           | atom
//   
//   ?atom  : NUMBER
//          | NAME
//          | "(" expr ")"
//   
//   %import common.NUMBER
//   %import common.CNAME -> NAME
//   %import common.WS_INLINE
//   %ignore WS_INLINE

#[allow(dead_code, unused_parens, clippy::all)]
pub mod parser {
use regex::Regex;
use std::collections::{HashMap, HashSet};
use std::fmt;

/// A parse-table cell: shift to a state, reduce by a rule, or accept.
#[derive(Clone, Copy)]
pub enum Action {
    Shift(u32),
    Reduce(u32),
    Accept,
}

/// A rule's tree-shaping metadata (everything the reducer needs, precomputed).
pub struct RuleData {
    pub origin: u32,
    pub len: u32,
    pub tree_name: &'static str,
    pub transparent: bool,
    pub expand1: bool,
    pub has_alias: bool,
    pub keep_all: bool,
    pub filter_pos: &'static [bool],
    pub placeholder_count: u32,
    pub is_start: bool,
}

/// Every per-grammar table a generated parser bakes. The generated file emits a
/// single `static DATA: GrammarData = …;` of this shape; the runtime is otherwise
/// grammar-agnostic.
pub struct GrammarData {
    /// Terminal ids occupy `[0, n_terminals)`; non-terminal GOTO index is
    /// `origin - n_terminals`.
    pub n_terminals: u32,
    /// Symbol name by id (token types + tree-node fallback + diagnostics).
    pub symbol_names: &'static [&'static str],
    pub rules: &'static [RuleData],
    /// `action[state]` is a sparse `(terminal id, action)` row.
    pub action: &'static [&'static [(u32, Action)]],
    /// `goto[state]` is a sparse `(nonterminal index, next state)` row.
    pub goto: &'static [&'static [(u32, u32)]],
    /// Start symbol name → initial state.
    pub start_states: &'static [(&'static str, u32)],
    pub start_default: &'static str,
    /// Leading inline-flag group for `g_regex_flags` (e.g. `(?i)`), or empty.
    pub global_prefix: &'static str,
    /// `(terminal id, inline regex)` in alternation order — the combined scanner.
    pub scan_groups: &'static [(u32, &'static str)],
    /// `unless` keyword retype: regex-terminal id → `(matched value, keyword id)`.
    pub unless: &'static [(u32, &'static [(&'static str, u32)])],
    /// `%ignore` terminal ids, discarded after matching.
    pub ignore: &'static [u32],
}

impl GrammarData {
    fn name_of(&self, id: u32) -> &'static str {
        self.symbol_names.get(id as usize).copied().unwrap_or("")
    }

    fn action_at(&self, state: usize, term: u32) -> Option<Action> {
        self.action[state]
            .iter()
            .find(|(t, _)| *t == term)
            .map(|(_, a)| *a)
    }

    fn goto_at(&self, state: usize, nt_index: u32) -> Option<u32> {
        self.goto[state]
            .iter()
            .find(|(n, _)| *n == nt_index)
            .map(|(_, s)| *s)
    }
}

/// A positioned token from the lexer.
#[derive(Clone, Debug)]
pub struct Token {
    pub type_id: u32,
    pub type_: String,
    pub value: String,
    pub line: usize,
    pub column: usize,
}

/// A child of a `Tree` node — a subtree, a leaf token, or a `None` placeholder.
#[derive(Clone, Debug)]
pub enum Child {
    Tree(Tree),
    Token(Token),
    None,
}

/// A node in the parse tree. `data` is the rule name (or alias) that built it.
#[derive(Clone, Debug)]
pub struct Tree {
    pub data: String,
    pub children: Vec<Child>,
}

/// The result of a parse — usually a `Tree`, but a `?start` rule that collapses
/// via expand1 to a single token yields that bare `Token`.
#[derive(Clone, Debug)]
pub enum ParseTree {
    Tree(Tree),
    Token(Token),
}

enum NodeValue {
    Token(Token),
    Tree(Tree),
    Inline(Vec<Child>),
}

impl fmt::Display for Tree {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let children: Vec<String> = self
            .children
            .iter()
            .map(|c| match c {
                Child::Tree(t) => t.to_string(),
                Child::Token(tok) => format!("Token({}, {:?})", tok.type_, tok.value),
                Child::None => "None".to_string(),
            })
            .collect();
        write!(f, "Tree({}, [{}])", self.data, children.join(", "))
    }
}

impl fmt::Display for ParseTree {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ParseTree::Tree(t) => write!(f, "{}", t),
            ParseTree::Token(tok) => write!(f, "Token({}, {:?})", tok.type_, tok.value),
        }
    }
}

// ───────────────────────────── lexer ─────────────────────────────

struct Scanner {
    re: Regex,
    /// (terminal id, capture-group index), in alternation order.
    groups: Vec<(u32, usize)>,
    unless: HashMap<u32, HashMap<String, u32>>,
}

impl Scanner {
    fn new(data: &GrammarData) -> Scanner {
        let mut parts: Vec<String> = Vec::with_capacity(data.scan_groups.len());
        for (id, rx) in data.scan_groups {
            parts.push(format!("(?P<g{}>{})", id, rx));
        }
        let pattern = format!("{}{}", data.global_prefix, parts.join("|"));
        let re = Regex::new(&pattern).expect("baked scanner regex is valid");
        // Resolve each group's name to its capture index (a terminal pattern can
        // itself contain groups, so the index is not the alternation position).
        let name_to_idx: HashMap<String, usize> = re
            .capture_names()
            .enumerate()
            .filter_map(|(i, n)| n.map(|n| (n.to_string(), i)))
            .collect();
        let groups = data
            .scan_groups
            .iter()
            .map(|(id, _)| (*id, name_to_idx[&format!("g{}", id)]))
            .collect();
        let mut unless: HashMap<u32, HashMap<String, u32>> = HashMap::new();
        for (re_id, entries) in data.unless {
            let m = unless.entry(*re_id).or_default();
            for (value, kw_id) in *entries {
                m.insert(value.to_string(), *kw_id);
            }
        }
        Scanner { re, groups, unless }
    }

    /// Match a single token starting exactly at `pos`. `None` = nothing here.
    fn match_at<'t>(&self, text: &'t str, pos: usize) -> Option<(u32, &'t str)> {
        let caps = self.re.captures_at(text, pos)?;
        let m0 = caps.get(0)?;
        // Accept only a non-empty match beginning exactly at `pos`.
        if m0.start() != pos || m0.end() == pos {
            return None;
        }
        let value = m0.as_str();
        for (id, idx) in &self.groups {
            if caps.get(*idx).is_some() {
                let ty = self
                    .unless
                    .get(id)
                    .and_then(|m| m.get(value))
                    .copied()
                    .unwrap_or(*id);
                return Some((ty, value));
            }
        }
        None
    }
}

fn lex(data: &GrammarData, scanner: &Scanner, text: &str) -> Result<Vec<Token>, String> {
    let ignore: HashSet<u32> = data.ignore.iter().copied().collect();
    let mut tokens = Vec::new();
    let mut pos = 0usize;
    let mut line = 1usize;
    let mut col = 1usize;

    while pos < text.len() {
        match scanner.match_at(text, pos) {
            Some((id, value)) => {
                let start_line = line;
                let start_col = col;
                for ch in value.chars() {
                    if ch == '\n' {
                        line += 1;
                        col = 1;
                    } else {
                        col += 1;
                    }
                }
                pos += value.len();
                if !ignore.contains(&id) {
                    tokens.push(Token {
                        type_id: id,
                        type_: data.name_of(id).to_string(),
                        value: value.to_string(),
                        line: start_line,
                        column: start_col,
                    });
                }
            }
            None => {
                let ch = text[pos..].chars().next().unwrap();
                return Err(format!(
                    "Unexpected character {:?} at line {}, column {}",
                    ch, line, col
                ));
            }
        }
    }

    // End-of-input sentinel (terminal id 0 = $END).
    tokens.push(Token {
        type_id: 0,
        type_: data.name_of(0).to_string(),
        value: String::new(),
        line,
        column: col,
    });
    Ok(tokens)
}

// ───────────────────────────── parser ─────────────────────────────

fn keep_token(rule: &RuleData, pos: usize) -> bool {
    rule.keep_all || !rule.filter_pos.get(pos).copied().unwrap_or(false)
}

fn shape(rule: &RuleData, mut children: Vec<Child>) -> NodeValue {
    for _ in 0..rule.placeholder_count {
        children.push(Child::None);
    }
    if rule.transparent {
        NodeValue::Inline(children)
    } else if rule.expand1
        && !rule.has_alias
        && children.len() == 1
        && !matches!(children[0], Child::None)
    {
        match children.pop().unwrap() {
            Child::Tree(t) => NodeValue::Tree(t),
            Child::Token(t) => NodeValue::Token(t),
            Child::None => unreachable!(),
        }
    } else {
        NodeValue::Tree(Tree {
            data: rule.tree_name.to_string(),
            children,
        })
    }
}

fn assemble(data: &GrammarData, rule_idx: usize, child_values: Vec<NodeValue>) -> NodeValue {
    let rule = &data.rules[rule_idx];
    let mut children: Vec<Child> = Vec::new();
    for (i, value) in child_values.into_iter().enumerate() {
        match value {
            NodeValue::Token(t) => {
                if keep_token(rule, i) {
                    children.push(Child::Token(t));
                }
            }
            NodeValue::Tree(t) => children.push(Child::Tree(t)),
            NodeValue::Inline(cs) => children.extend(cs),
        }
    }
    shape(rule, children)
}

fn run(data: &GrammarData, tokens: &[Token], start_state: usize) -> Result<ParseTree, String> {
    let mut state_stack: Vec<usize> = vec![start_state];
    let mut value_stack: Vec<NodeValue> = Vec::new();
    let mut i = 0usize;

    loop {
        let state = *state_stack.last().unwrap();
        let token = &tokens[i];
        match data.action_at(state, token.type_id) {
            Some(Action::Shift(ns)) => {
                i += 1;
                state_stack.push(ns as usize);
                value_stack.push(NodeValue::Token(token.clone()));
            }
            Some(Action::Reduce(r)) => {
                let rule = &data.rules[r as usize];
                let len = rule.len as usize;
                let child_values: Vec<NodeValue> = value_stack.split_off(value_stack.len() - len);
                for _ in 0..len {
                    state_stack.pop();
                }
                let value = assemble(data, r as usize, child_values);
                let top = *state_stack.last().unwrap();
                let nt_index = rule.origin - data.n_terminals;
                let next = data.goto_at(top, nt_index).expect("missing goto entry");
                state_stack.push(next as usize);
                value_stack.push(value);
            }
            Some(Action::Accept) => {
                return match value_stack.pop() {
                    Some(NodeValue::Tree(t)) => Ok(ParseTree::Tree(t)),
                    Some(NodeValue::Token(t)) => Ok(ParseTree::Token(t)),
                    _ => Err("accept with empty value stack".to_string()),
                };
            }
            None => {
                let expected: Vec<&str> = data.action[state]
                    .iter()
                    .map(|(t, _)| data.name_of(*t))
                    .collect();
                if token.type_id == 0 {
                    return Err(format!(
                        "Unexpected end of input at line {}, column {}. Expected one of: {:?}",
                        token.line, token.column, expected
                    ));
                }
                return Err(format!(
                    "Unexpected token {:?} ({}) at line {}, column {}. Expected one of: {:?}",
                    token.value, token.type_, token.line, token.column, expected
                ));
            }
        }
    }
}

fn start_state_for(data: &GrammarData, start: Option<&str>) -> Result<usize, String> {
    let name = start.unwrap_or(data.start_default);
    for (n, s) in data.start_states {
        if *n == name {
            return Ok(*s as usize);
        }
    }
    Err(format!("unknown start symbol {:?}", name))
}

/// A self-contained parser over a baked [`GrammarData`].
pub struct Parser {
    data: &'static GrammarData,
    scanner: Scanner,
}

impl Parser {
    /// Build a parser for the given baked grammar (compiles the lexer regex once).
    /// The generated file adds a `Parser::new()` that calls this with its `&DATA`.
    pub fn from_data(data: &'static GrammarData) -> Parser {
        let scanner = Scanner::new(data);
        Parser { data, scanner }
    }

    /// Parse `text` from the default start symbol.
    pub fn parse(&self, text: &str) -> Result<ParseTree, String> {
        self.parse_from(text, None)
    }

    /// Parse `text` from the named start symbol.
    pub fn parse_from(&self, text: &str, start: Option<&str>) -> Result<ParseTree, String> {
        let tokens = lex(self.data, &self.scanner, text)?;
        let start_state = start_state_for(self.data, start)?;
        run(self.data, &tokens, start_state)
    }
}


// ── baked grammar tables ──
static DATA: GrammarData = GrammarData {
    n_terminals: 10,
    symbol_names: &[
        "$END",
        "NAME",
        "NUMBER",
        "__IGNORE_0",
        "LPAR",
        "MINUS",
        "PLUS",
        "RPAR",
        "SLASH",
        "STAR",
        "$root_start",
        "start",
        "expr",
        "term",
        "factor",
        "atom",
    ],
    rules: &[
        RuleData { origin: 11, len: 1, tree_name: "start", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, is_start: false },
        RuleData { origin: 12, len: 3, tree_name: "add", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[false, true, false], placeholder_count: 0, is_start: false },
        RuleData { origin: 12, len: 3, tree_name: "sub", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[false, true, false], placeholder_count: 0, is_start: false },
        RuleData { origin: 12, len: 1, tree_name: "expr", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, is_start: false },
        RuleData { origin: 13, len: 3, tree_name: "mul", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[false, true, false], placeholder_count: 0, is_start: false },
        RuleData { origin: 13, len: 3, tree_name: "div", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[false, true, false], placeholder_count: 0, is_start: false },
        RuleData { origin: 13, len: 1, tree_name: "term", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, is_start: false },
        RuleData { origin: 14, len: 2, tree_name: "pos", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[true, false], placeholder_count: 0, is_start: false },
        RuleData { origin: 14, len: 2, tree_name: "neg", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[true, false], placeholder_count: 0, is_start: false },
        RuleData { origin: 14, len: 1, tree_name: "factor", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, is_start: false },
        RuleData { origin: 15, len: 1, tree_name: "atom", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, is_start: false },
        RuleData { origin: 15, len: 1, tree_name: "atom", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, is_start: false },
        RuleData { origin: 15, len: 3, tree_name: "atom", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[true, false, true], placeholder_count: 0, is_start: false },
        RuleData { origin: 10, len: 1, tree_name: "$root_start", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, is_start: true },
    ],
    action: &[
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5))],
        &[(0, Action::Reduce(11)), (5, Action::Reduce(11)), (6, Action::Reduce(11)), (7, Action::Reduce(11)), (8, Action::Reduce(11)), (9, Action::Reduce(11))],
        &[(0, Action::Reduce(10)), (5, Action::Reduce(10)), (6, Action::Reduce(10)), (7, Action::Reduce(10)), (8, Action::Reduce(10)), (9, Action::Reduce(10))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5))],
        &[(0, Action::Accept)],
        &[(0, Action::Reduce(0)), (5, Action::Shift(14)), (6, Action::Shift(15))],
        &[(0, Action::Reduce(3)), (5, Action::Reduce(3)), (6, Action::Reduce(3)), (7, Action::Reduce(3)), (8, Action::Shift(16)), (9, Action::Shift(17))],
        &[(0, Action::Reduce(6)), (5, Action::Reduce(6)), (6, Action::Reduce(6)), (7, Action::Reduce(6)), (8, Action::Reduce(6)), (9, Action::Reduce(6))],
        &[(0, Action::Reduce(9)), (5, Action::Reduce(9)), (6, Action::Reduce(9)), (7, Action::Reduce(9)), (8, Action::Reduce(9)), (9, Action::Reduce(9))],
        &[(5, Action::Shift(14)), (6, Action::Shift(15)), (7, Action::Shift(18))],
        &[(0, Action::Reduce(8)), (5, Action::Reduce(8)), (6, Action::Reduce(8)), (7, Action::Reduce(8)), (8, Action::Reduce(8)), (9, Action::Reduce(8))],
        &[(0, Action::Reduce(7)), (5, Action::Reduce(7)), (6, Action::Reduce(7)), (7, Action::Reduce(7)), (8, Action::Reduce(7)), (9, Action::Reduce(7))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5))],
        &[(0, Action::Reduce(12)), (5, Action::Reduce(12)), (6, Action::Reduce(12)), (7, Action::Reduce(12)), (8, Action::Reduce(12)), (9, Action::Reduce(12))],
        &[(0, Action::Reduce(2)), (5, Action::Reduce(2)), (6, Action::Reduce(2)), (7, Action::Reduce(2)), (8, Action::Shift(16)), (9, Action::Shift(17))],
        &[(0, Action::Reduce(1)), (5, Action::Reduce(1)), (6, Action::Reduce(1)), (7, Action::Reduce(1)), (8, Action::Shift(16)), (9, Action::Shift(17))],
        &[(0, Action::Reduce(5)), (5, Action::Reduce(5)), (6, Action::Reduce(5)), (7, Action::Reduce(5)), (8, Action::Reduce(5)), (9, Action::Reduce(5))],
        &[(0, Action::Reduce(4)), (5, Action::Reduce(4)), (6, Action::Reduce(4)), (7, Action::Reduce(4)), (8, Action::Reduce(4)), (9, Action::Reduce(4))],
    ],
    goto: &[
        &[(1, 6), (2, 7), (3, 8), (4, 9), (5, 10)],
        &[],
        &[],
        &[(2, 11), (3, 8), (4, 9), (5, 10)],
        &[(4, 12), (5, 10)],
        &[(4, 13), (5, 10)],
        &[],
        &[],
        &[],
        &[],
        &[],
        &[],
        &[],
        &[],
        &[(3, 19), (4, 9), (5, 10)],
        &[(3, 20), (4, 9), (5, 10)],
        &[(4, 21), (5, 10)],
        &[(4, 22), (5, 10)],
        &[],
        &[],
        &[],
        &[],
        &[],
    ],
    start_states: &[("start", 0)],
    start_default: "start",
    global_prefix: "",
    scan_groups: &[
        (2, "(?:(?:(?:(?:(?:(?:(?:(?:[0-9]))+)\\.(?:(?:(?:(?:[0-9]))+))?)|(?:\\.(?:(?:(?:[0-9]))+)))(?:(?:(?:e|E)(?:(?:\\+|\\-)?(?:(?:(?:[0-9]))+))))?)|(?:(?:(?:(?:[0-9]))+)(?:(?:e|E)(?:(?:\\+|\\-)?(?:(?:(?:[0-9]))+))))))|(?:(?:(?:(?:[0-9]))+))"),
        (1, "(?:_|(?:(?:(?:[A-Z]))|(?:(?:[a-z]))))(?:(?:_|(?:(?:(?:[A-Z]))|(?:(?:[a-z])))|(?:[0-9])))*"),
        (3, "(?:(?: |\\t))+"),
        (4, "\\("),
        (5, "\\-"),
        (6, "\\+"),
        (7, "\\)"),
        (9, "\\*"),
        (8, "/"),
    ],
    unless: &[
    ],
    ignore: &[3],
};

impl Parser {
    /// Construct the parser for this baked grammar.
    pub fn new() -> Parser {
        Parser::from_data(&DATA)
    }
}

impl Default for Parser {
    fn default() -> Self {
        Parser::new()
    }
}
}

#[allow(unused_imports)]
pub use parser::{Child, ParseTree, Parser, Token, Tree};
