// @generated by `lark-rs generate-parser` — DO NOT EDIT.
//
// A self-contained LALR parser. Depends only on the `regex` crate and the
// Rust standard library — not on lark-rs. Drop it into any crate that has
// `regex` as a dependency and call `Parser::new().parse(text)`.
//
// Source grammar:
//   ?start: value
//
//   ?value: object
//         | array
//         | string
//         | SIGNED_NUMBER      -> number
//         | "true"             -> true
//         | "false"            -> false
//         | "null"             -> null
//
//   array  : "[" _WS? [value ("," _WS? value)*] "]"
//   object : "{" _WS? [pair ("," _WS? pair)*] "}"
//   pair   : string ":" _WS value
//
//   string : ESCAPED_STRING
//
//   %import common.ESCAPED_STRING
//   %import common.SIGNED_NUMBER
//   %import common.WS -> _WS

#[allow(dead_code, unused_parens, clippy::all)]
pub mod parser {
use regex::Regex;
use std::collections::{HashMap, HashSet};
use std::fmt;

/// A parse-table cell: shift to a state, reduce by a rule, or accept.
#[derive(Clone, Copy)]
pub enum Action {
    Shift(u32),
    Reduce(u32),
    Accept,
}

/// A rule's tree-shaping metadata (everything the reducer needs, precomputed).
pub struct RuleData {
    pub origin: u32,
    pub len: u32,
    pub tree_name: &'static str,
    pub transparent: bool,
    pub expand1: bool,
    pub has_alias: bool,
    pub keep_all: bool,
    pub filter_pos: &'static [bool],
    pub placeholder_count: u32,
    /// `None` placeholders a distributed absent `[...]` left before each
    /// expansion position (entry `len` is trailing); empty for ordinary rules.
    pub nones_before: &'static [u32],
    pub is_start: bool,
}

/// Every per-grammar table a generated parser bakes. The generated file emits a
/// single `static DATA: GrammarData = …;` of this shape; the runtime is otherwise
/// grammar-agnostic.
pub struct GrammarData {
    /// Terminal ids occupy `[0, n_terminals)`; non-terminal GOTO index is
    /// `origin - n_terminals`.
    pub n_terminals: u32,
    /// Symbol name by id (token types + tree-node fallback + diagnostics).
    pub symbol_names: &'static [&'static str],
    pub rules: &'static [RuleData],
    /// `action[state]` is a sparse `(terminal id, action)` row.
    pub action: &'static [&'static [(u32, Action)]],
    /// `goto[state]` is a sparse `(nonterminal index, next state)` row.
    pub goto: &'static [&'static [(u32, u32)]],
    /// Start symbol name → initial state.
    pub start_states: &'static [(&'static str, u32)],
    pub start_default: &'static str,
    /// Leading inline-flag group for `g_regex_flags` (e.g. `(?i)`), or empty.
    pub global_prefix: &'static str,
    /// `(terminal id, inline regex)` in alternation order — the combined scanner.
    pub scan_groups: &'static [(u32, &'static str)],
    /// `unless` keyword retype: regex-terminal id → `(keyword value,
    /// case-insensitive, keyword id)`, in definition order.
    pub unless: &'static [(u32, &'static [(&'static str, bool, u32)])],
    /// `%ignore` terminal ids, discarded after matching.
    pub ignore: &'static [u32],
    /// Python Lark's `propagate_positions`: when true a non-transparent node's
    /// `meta` span is widened to its rule's **pre-filter** children (so a filtered
    /// `"("`/`")"` still bounds the parent — #402), byte-identical to the in-process
    /// LALR engine's `TreeOutputBuilder::with_propagate_positions`. When false the
    /// span is still populated from the (already-filtered) children, exactly as the
    /// in-process default does — `propagate_positions` only changes *which* children
    /// feed the span, never whether `meta` exists.
    pub propagate_positions: bool,
}

impl GrammarData {
    fn name_of(&self, id: u32) -> &'static str {
        self.symbol_names.get(id as usize).copied().unwrap_or("")
    }

    fn action_at(&self, state: usize, term: u32) -> Option<Action> {
        self.action[state]
            .iter()
            .find(|(t, _)| *t == term)
            .map(|(_, a)| *a)
    }

    fn goto_at(&self, state: usize, nt_index: u32) -> Option<u32> {
        self.goto[state]
            .iter()
            .find(|(n, _)| *n == nt_index)
            .map(|(_, s)| *s)
    }
}

/// A positioned token from the lexer.
///
/// `start_pos`/`end_pos` are **character** indices, not byte offsets — Python
/// Lark's `start_pos`/`end_pos` are char indices and the two diverge on any
/// non-ASCII input (#278). `end_line`/`end_column` are the 1-based position just
/// past the token (multi-line aware), matching the in-process `BasicLexer`.
#[derive(Clone, Debug)]
pub struct Token {
    pub type_id: u32,
    pub type_: String,
    pub value: String,
    pub line: usize,
    pub column: usize,
    pub end_line: usize,
    pub end_column: usize,
    pub start_pos: usize,
    pub end_pos: usize,
}

/// A child of a `Tree` node — a subtree, a leaf token, or a `None` placeholder.
#[derive(Clone, Debug)]
pub enum Child {
    Tree(Tree),
    Token(Token),
    None,
}

/// Source position metadata attached to a [`Tree`] node — the standalone mirror
/// of the in-process `tree::Meta`. Populated for every node (a node with no
/// positioned child stays `empty=true` with `None` fields). Under
/// `propagate_positions` the span is widened to the rule's pre-filter children,
/// byte-identical to the in-process LALR engine (#402).
#[derive(Clone, Debug)]
pub struct Meta {
    pub line: Option<usize>,
    pub column: Option<usize>,
    pub end_line: Option<usize>,
    pub end_column: Option<usize>,
    pub start_pos: Option<usize>,
    pub end_pos: Option<usize>,
    /// True when no child contributed a position (an empty match).
    pub empty: bool,
}

impl Default for Meta {
    /// A position-less default `Meta` is `empty: true`: with no positioned child
    /// there is no span, so the node is empty — the semantic convention Python Lark
    /// follows (`Meta.empty` defaults `True`) and that `from_children` enforces. The
    /// *derived* `Default` would give `empty: false`, which is semantically wrong for
    /// a hand-constructed/default value. Parser construction is unaffected: every
    /// engine-built `Meta` sets `empty` explicitly afterwards (`from_children`
    /// recomputes it from the children; `observe_token` builds a positioned `Meta`
    /// directly), so this only matters for default/hand-built values. Position fields
    /// default to their natural zero (`None`).
    fn default() -> Self {
        Meta {
            line: None,
            column: None,
            end_line: None,
            end_column: None,
            start_pos: None,
            end_pos: None,
            empty: true,
        }
    }
}

impl Meta {
    /// Base span from the **post-filter** children: the first positioned child
    /// fixes the start fields, the last positioned child the end fields. Mirrors
    /// `tree::Meta::from_children` (and Python's `_pp_get_meta`): a positionless
    /// empty subtree contributes nothing, so a node whose sole child is one stays
    /// `empty=true`.
    fn from_children(children: &[Child]) -> Meta {
        let mut meta = Meta::default();
        for child in children {
            if let (None, Some(line)) = (meta.line, child_line(child)) {
                meta.line = Some(line);
                meta.column = child_column(child);
                meta.start_pos = child_start(child);
            }
        }
        for child in children.iter().rev() {
            if let Some(line) = child_end_line(child) {
                meta.end_line = Some(line);
                meta.end_column = child_end_column(child);
                meta.end_pos = child_end(child);
                break;
            }
        }
        meta.empty = meta.line.is_none();
        meta
    }
}

fn child_line(c: &Child) -> Option<usize> {
    match c {
        Child::Token(t) if t.line > 0 => Some(t.line),
        Child::Tree(t) => t.meta.line,
        _ => None,
    }
}
fn child_column(c: &Child) -> Option<usize> {
    match c {
        Child::Token(t) if t.column > 0 => Some(t.column),
        Child::Tree(t) => t.meta.column,
        _ => None,
    }
}
fn child_start(c: &Child) -> Option<usize> {
    match c {
        Child::Token(t) => Some(t.start_pos),
        Child::Tree(t) => t.meta.start_pos,
        Child::None => None,
    }
}
fn child_end_line(c: &Child) -> Option<usize> {
    match c {
        Child::Token(t) if t.end_line > 0 => Some(t.end_line),
        Child::Tree(t) => t.meta.end_line,
        _ => None,
    }
}
fn child_end_column(c: &Child) -> Option<usize> {
    match c {
        Child::Token(t) if t.end_column > 0 => Some(t.end_column),
        Child::Tree(t) => t.meta.end_column,
        _ => None,
    }
}
fn child_end(c: &Child) -> Option<usize> {
    match c {
        Child::Token(t) => Some(t.end_pos),
        Child::Tree(t) => t.meta.end_pos,
        Child::None => None,
    }
}

/// A node in the parse tree. `data` is the rule name (or alias) that built it.
///
/// `Drop` and `Clone` are manual worklist implementations (#151, same as the
/// main crate's `Tree`): the derived glue recurses to tree depth, and a parse
/// result is as deep as the input is nested, so the derived glue overflows
/// small native stacks.
#[derive(Debug)]
pub struct Tree {
    pub data: String,
    pub children: Vec<Child>,
    pub meta: Meta,
}

impl Drop for Tree {
    fn drop(&mut self) {
        let is_tree = |c: &Child| matches!(c, Child::Tree(_));
        // Fast path: leaf-only children drop in place — no recursion possible.
        if !self.children.iter().any(is_tree) {
            return;
        }
        // Worklist of whole `children` vectors (3-word moves, never per-element
        // copies). Invariant: a vector is pushed only if it contains a subtree
        // with sub-subtrees; every `Tree` value therefore reaches its own
        // (recursive) drop with empty or leaf-only children, where the fast
        // path returns immediately — so native depth stays constant.
        let mut stack: Vec<Vec<Child>> = vec![std::mem::take(&mut self.children)];
        while let Some(mut vec) = stack.pop() {
            for child in vec.iter_mut() {
                if let Child::Tree(t) = child {
                    if t.children.iter().any(is_tree) {
                        stack.push(std::mem::take(&mut t.children));
                    }
                }
            }
            // `vec` drops here; every tree in it is now empty or leaf-only.
        }
    }
}

impl Clone for Tree {
    fn clone(&self) -> Self {
        // Explicit-frame deep copy: one heap frame per open node instead of one
        // native frame per tree level.
        struct Frame<'a> {
            src: std::slice::Iter<'a, Child>,
            data: String,
            meta: Meta,
            out: Vec<Child>,
        }
        fn frame(t: &Tree) -> Frame<'_> {
            Frame {
                src: t.children.iter(),
                data: t.data.clone(),
                meta: t.meta.clone(),
                out: Vec::with_capacity(t.children.len()),
            }
        }
        let mut stack = vec![frame(self)];
        loop {
            let top = stack
                .last_mut()
                .expect("clone stack never empties mid-walk");
            match top.src.next() {
                Some(Child::Tree(t)) => stack.push(frame(t)),
                Some(Child::Token(tok)) => top.out.push(Child::Token(tok.clone())),
                Some(Child::None) => top.out.push(Child::None),
                None => {
                    let done = stack.pop().expect("just peeked");
                    let tree = Tree {
                        data: done.data,
                        children: done.out,
                        meta: done.meta,
                    };
                    match stack.last_mut() {
                        Some(parent) => parent.out.push(Child::Tree(tree)),
                        None => return tree,
                    }
                }
            }
        }
    }
}

/// The result of a parse — usually a `Tree`, but a `?start` rule that collapses
/// via expand1 to a single token yields that bare `Token`, and a `?start` whose
/// sole alternative is an absent `[...]` placeholder collapses to a bare `None`
/// (Python's literal `None` result for `?start: [A]` on `""` with
/// `maybe_placeholders`, #289/#382). Mirrors the public API's `ParseTree::None`
/// (ADR-0033) so the bake stays byte-faithful to core.
#[derive(Clone, Debug)]
pub enum ParseTree {
    Tree(Tree),
    Token(Token),
    None,
}

enum NodeValue {
    Token(Token),
    Tree(Tree),
    Inline(Vec<Child>),
}

impl fmt::Display for Tree {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let children: Vec<String> = self
            .children
            .iter()
            .map(|c| match c {
                Child::Tree(t) => t.to_string(),
                Child::Token(tok) => format!("Token({}, {:?})", tok.type_, tok.value),
                Child::None => "None".to_string(),
            })
            .collect();
        write!(f, "Tree({}, [{}])", self.data, children.join(", "))
    }
}

impl fmt::Display for ParseTree {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ParseTree::Tree(t) => write!(f, "{}", t),
            ParseTree::Token(tok) => write!(f, "Token({}, {:?})", tok.type_, tok.value),
            ParseTree::None => write!(f, "None"),
        }
    }
}

// ───────────────────────────── lexer ─────────────────────────────

struct Scanner {
    re: Regex,
    /// (terminal id, capture-group index), in alternation order.
    groups: Vec<(u32, usize)>,
    /// Keyword retype per regex terminal: exact values hashed, `"..."i`
    /// keywords as anchored case-insensitive regexes (definition order).
    unless: HashMap<u32, (HashMap<String, u32>, Vec<(Regex, u32)>)>,
}

impl Scanner {
    fn new(data: &GrammarData) -> Scanner {
        let mut parts: Vec<String> = Vec::with_capacity(data.scan_groups.len());
        for (id, rx) in data.scan_groups {
            parts.push(format!("(?P<g{}>{})", id, rx));
        }
        let pattern = format!("{}{}", data.global_prefix, parts.join("|"));
        let re = Regex::new(&pattern).expect("baked scanner regex is valid");
        // Resolve each group's name to its capture index (a terminal pattern can
        // itself contain groups, so the index is not the alternation position).
        let name_to_idx: HashMap<String, usize> = re
            .capture_names()
            .enumerate()
            .filter_map(|(i, n)| n.map(|n| (n.to_string(), i)))
            .collect();
        let groups = data
            .scan_groups
            .iter()
            .map(|(id, _)| (*id, name_to_idx[&format!("g{}", id)]))
            .collect();
        let mut unless: HashMap<u32, (HashMap<String, u32>, Vec<(Regex, u32)>)> = HashMap::new();
        for (re_id, entries) in data.unless {
            let slot = unless.entry(*re_id).or_default();
            for (value, ci, kw_id) in *entries {
                if *ci {
                    let src = format!("^(?i:{})$", regex::escape(value));
                    let re = Regex::new(&src).expect("baked unless regex is valid");
                    slot.1.push((re, *kw_id));
                } else {
                    slot.0.entry(value.to_string()).or_insert(*kw_id);
                }
            }
        }
        Scanner { re, groups, unless }
    }

    /// Match a single token starting exactly at `pos`. `None` = nothing here.
    fn match_at<'t>(&self, text: &'t str, pos: usize) -> Option<(u32, &'t str)> {
        let caps = self.re.captures_at(text, pos)?;
        let m0 = caps.get(0)?;
        // Accept only a non-empty match beginning exactly at `pos`.
        if m0.start() != pos || m0.end() == pos {
            return None;
        }
        let value = m0.as_str();
        for (id, idx) in &self.groups {
            if caps.get(*idx).is_some() {
                let ty = self
                    .unless
                    .get(id)
                    .and_then(|(exact, ci)| {
                        exact.get(value).copied().or_else(|| {
                            ci.iter()
                                .find(|(re, _)| re.is_match(value))
                                .map(|(_, k)| *k)
                        })
                    })
                    .unwrap_or(*id);
                return Some((ty, value));
            }
        }
        None
    }
}

fn lex(data: &GrammarData, scanner: &Scanner, text: &str) -> Result<Vec<Token>, String> {
    let ignore: HashSet<u32> = data.ignore.iter().copied().collect();
    let mut tokens = Vec::new();
    // `pos` is the **byte** offset (drives regex slicing); `char_pos` is the
    // **character** index a token's `start_pos`/`end_pos` carry — Python parity,
    // the two diverge on non-ASCII input (#278). Both advance together.
    let mut pos = 0usize;
    let mut char_pos = 0usize;
    let mut line = 1usize;
    let mut col = 1usize;

    while pos < text.len() {
        match scanner.match_at(text, pos) {
            Some((id, value)) => {
                let start_line = line;
                let start_col = col;
                let start_pos = char_pos;
                for ch in value.chars() {
                    if ch == '\n' {
                        line += 1;
                        col = 1;
                    } else {
                        col += 1;
                    }
                    char_pos += 1;
                }
                pos += value.len();
                if !ignore.contains(&id) {
                    tokens.push(Token {
                        type_id: id,
                        type_: data.name_of(id).to_string(),
                        value: value.to_string(),
                        line: start_line,
                        column: start_col,
                        end_line: line,
                        end_column: col,
                        start_pos,
                        end_pos: char_pos,
                    });
                }
            }
            None => {
                let ch = text[pos..].chars().next().unwrap();
                return Err(format!(
                    "Unexpected character {:?} at line {}, column {}",
                    ch, line, col
                ));
            }
        }
    }

    // End-of-input sentinel (terminal id 0 = $END); carries the char index (#278).
    tokens.push(Token {
        type_id: 0,
        type_: data.name_of(0).to_string(),
        value: String::new(),
        line,
        column: col,
        end_line: line,
        end_column: col,
        start_pos: char_pos,
        end_pos: char_pos,
    });
    Ok(tokens)
}

// ───────────────────────────── parser ─────────────────────────────

fn keep_token(rule: &RuleData, pos: usize) -> bool {
    rule.keep_all || !rule.filter_pos.get(pos).copied().unwrap_or(false)
}

fn nones_at(rule: &RuleData, gap: usize) -> u32 {
    rule.nones_before.get(gap).copied().unwrap_or(0)
}

/// The container span of a rule's **pre-filter** children — the first/last
/// positioned child's start/end, including filtered punctuation tokens the tree
/// drops. The standalone mirror of `tree_builder::ContainerSpan` (Python's
/// `PropagatePositions._pp_get_meta`), the #402 regression net: built by streaming
/// every child value past `observe_*` left-to-right, then applied with `widen_meta`.
#[derive(Default)]
struct ContainerSpan {
    first: Option<Meta>,
    last: Option<Meta>,
}

impl ContainerSpan {
    fn observe(&mut self, meta: Meta) {
        if self.first.is_none() {
            self.first = Some(meta.clone());
        }
        self.last = Some(meta);
    }

    fn observe_token(&mut self, t: &Token) {
        self.observe(Meta {
            line: Some(t.line),
            column: Some(t.column),
            end_line: Some(t.end_line),
            end_column: Some(t.end_column),
            start_pos: Some(t.start_pos),
            end_pos: Some(t.end_pos),
            empty: false,
        });
    }

    fn observe_meta(&mut self, meta: &Meta) {
        if !meta.empty && meta.line.is_some() {
            self.observe(meta.clone());
        }
    }

    fn observe_child(&mut self, c: &Child) {
        match c {
            Child::Token(t) => self.observe_token(t),
            Child::Tree(t) => self.observe_meta(&t.meta),
            Child::None => {}
        }
    }

    /// Widen `meta`'s span to the container: start fields from the first positioned
    /// child, end fields from the last. A node with no positioned pre-filter child
    /// is left untouched (an empty production).
    fn widen_meta(&self, meta: &mut Meta) {
        if let Some(first) = &self.first {
            meta.line = first.line;
            meta.column = first.column;
            meta.start_pos = first.start_pos;
            meta.empty = false;
        }
        if let Some(last) = &self.last {
            meta.end_line = last.end_line;
            meta.end_column = last.end_column;
            meta.end_pos = last.end_pos;
            meta.empty = false;
        }
    }
}

fn shape(
    data: &GrammarData,
    rule: &RuleData,
    mut children: Vec<Child>,
    container: ContainerSpan,
) -> NodeValue {
    for _ in 0..rule.placeholder_count {
        children.push(Child::None);
    }
    for _ in 0..nones_at(rule, rule.len as usize) {
        children.push(Child::None);
    }
    if rule.transparent {
        // `_rule` / `__anon_*`: splice into the parent. No node is built, so there
        // is no `meta` to widen — the spliced children carry their own positions up.
        NodeValue::Inline(children)
    } else if rule.expand1 && !rule.has_alias && children.len() == 1 {
        // `?rule` with a single child: return that child directly. A lone `None`
        // placeholder (`?w: [A]` on the absent branch) collapses exactly like a
        // real single child — Python/core yield `start[None]`, not `start[w[None]]`
        // (bounty RC9; the `?` collapse is purely arity-1, never value-typed). This
        // mirrors `TreeOutputBuilder::shape`'s RC9 carve-out in
        // `parsers/tree_builder.rs` so the baked runtime stays byte-faithful to core.
        //
        // No container widening here: Python's `PropagatePositions` only sets meta
        // when its node builder returns a `Tree`; an expand1 collapse to a bare
        // token/tree keeps that value's own span.
        match children.pop().unwrap() {
            Child::Tree(t) => NodeValue::Tree(t),
            Child::Token(t) => NodeValue::Token(t),
            // A bare `None` has no Token/Tree slot; carry it as a single-None
            // inline so the parent splices exactly one `Child::None` in place.
            Child::None => NodeValue::Inline(vec![Child::None]),
        }
    } else {
        let mut meta = Meta::from_children(&children);
        if data.propagate_positions {
            container.widen_meta(&mut meta);
        }
        NodeValue::Tree(Tree {
            data: rule.tree_name.to_string(),
            children,
            meta,
        })
    }
}

fn assemble(data: &GrammarData, rule_idx: usize, child_values: Vec<NodeValue>) -> NodeValue {
    let rule = &data.rules[rule_idx];
    let mut children: Vec<Child> = Vec::new();
    // Under `propagate_positions`, the node's span comes from the *pre*-filter
    // children (so a filtered `"("`/`")"` still bounds the span — #402), so observe
    // every value as it streams by, kept or dropped, before the kept list is shaped.
    let mut container = ContainerSpan::default();
    for (i, value) in child_values.into_iter().enumerate() {
        for _ in 0..nones_at(rule, i) {
            children.push(Child::None);
        }
        match value {
            NodeValue::Token(t) => {
                if data.propagate_positions {
                    container.observe_token(&t);
                }
                if keep_token(rule, i) {
                    children.push(Child::Token(t));
                }
            }
            NodeValue::Tree(t) => {
                if data.propagate_positions {
                    container.observe_meta(&t.meta);
                }
                children.push(Child::Tree(t));
            }
            NodeValue::Inline(cs) => {
                if data.propagate_positions {
                    for c in &cs {
                        container.observe_child(c);
                    }
                }
                children.extend(cs);
            }
        }
    }
    shape(data, rule, children, container)
}

fn run(data: &GrammarData, tokens: &[Token], start_state: usize) -> Result<ParseTree, String> {
    let mut state_stack: Vec<usize> = vec![start_state];
    let mut value_stack: Vec<NodeValue> = Vec::new();
    let mut i = 0usize;

    loop {
        let state = *state_stack.last().unwrap();
        let token = &tokens[i];
        match data.action_at(state, token.type_id) {
            Some(Action::Shift(ns)) => {
                i += 1;
                state_stack.push(ns as usize);
                value_stack.push(NodeValue::Token(token.clone()));
            }
            Some(Action::Reduce(r)) => {
                let rule = &data.rules[r as usize];
                let len = rule.len as usize;
                let child_values: Vec<NodeValue> = value_stack.split_off(value_stack.len() - len);
                for _ in 0..len {
                    state_stack.pop();
                }
                let value = assemble(data, r as usize, child_values);
                let top = *state_stack.last().unwrap();
                let nt_index = rule.origin - data.n_terminals;
                let next = data.goto_at(top, nt_index).expect("missing goto entry");
                state_stack.push(next as usize);
                value_stack.push(value);
            }
            Some(Action::Accept) => {
                return match value_stack.pop() {
                    Some(NodeValue::Tree(t)) => Ok(ParseTree::Tree(t)),
                    Some(NodeValue::Token(t)) => Ok(ParseTree::Token(t)),
                    // A top-level `?start` collapsing a lone-`None` placeholder
                    // (`?start: [A]` on `""`) reaches accept as `Inline([None])`
                    // (the RC9 collapse in `shape`). Python Lark and every in-process
                    // backend return a bare `None` here, so emit `ParseTree::None`
                    // to match the oracle (#289/#382, ADR-0033; mirrors `lalr.rs`).
                    Some(NodeValue::Inline(cs))
                        if cs.len() == 1 && matches!(cs[0], Child::None) =>
                    {
                        Ok(ParseTree::None)
                    }
                    _ => Err("accept with empty value stack".to_string()),
                };
            }
            None => {
                let expected: Vec<&str> = data.action[state]
                    .iter()
                    .map(|(t, _)| data.name_of(*t))
                    .collect();
                if token.type_id == 0 {
                    return Err(format!(
                        "Unexpected end of input at line {}, column {}. Expected one of: {:?}",
                        token.line, token.column, expected
                    ));
                }
                return Err(format!(
                    "Unexpected token {:?} ({}) at line {}, column {}. Expected one of: {:?}",
                    token.value, token.type_, token.line, token.column, expected
                ));
            }
        }
    }
}

fn start_state_for(data: &GrammarData, start: Option<&str>) -> Result<usize, String> {
    let name = start.unwrap_or(data.start_default);
    for (n, s) in data.start_states {
        if *n == name {
            return Ok(*s as usize);
        }
    }
    Err(format!("unknown start symbol {:?}", name))
}

/// A self-contained parser over a baked [`GrammarData`].
pub struct Parser {
    data: &'static GrammarData,
    scanner: Scanner,
}

impl Parser {
    /// Build a parser for the given baked grammar (compiles the lexer regex once).
    /// The generated file adds a `Parser::new()` that calls this with its `&DATA`.
    pub fn from_data(data: &'static GrammarData) -> Parser {
        let scanner = Scanner::new(data);
        Parser { data, scanner }
    }

    /// Parse `text` from the default start symbol.
    pub fn parse(&self, text: &str) -> Result<ParseTree, String> {
        self.parse_from(text, None)
    }

    /// Parse `text` from the named start symbol.
    pub fn parse_from(&self, text: &str, start: Option<&str>) -> Result<ParseTree, String> {
        let tokens = lex(self.data, &self.scanner, text)?;
        let start_state = start_state_for(self.data, start)?;
        run(self.data, &tokens, start_state)
    }
}


// ── baked grammar tables ──
static DATA: GrammarData = GrammarData {
    n_terminals: 13,
    symbol_names: &[
        "$END",
        "SIGNED_NUMBER",
        "ESCAPED_STRING",
        "_WS",
        "FALSE",
        "NULL",
        "TRUE",
        "COLON",
        "COMMA",
        "LBRACE",
        "LSQB",
        "RBRACE",
        "RSQB",
        "$root_start",
        "start",
        "value",
        "__anon_plus_0",
        "array",
        "__anon_plus_1",
        "object",
        "pair",
        "string",
    ],
    rules: &[
        RuleData { origin: 14, len: 1, tree_name: "start", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 15, len: 1, tree_name: "value", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 15, len: 1, tree_name: "value", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 15, len: 1, tree_name: "value", transparent: false, expand1: true, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 15, len: 1, tree_name: "number", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 15, len: 1, tree_name: "true", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 15, len: 1, tree_name: "false", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 15, len: 1, tree_name: "null", transparent: false, expand1: true, has_alias: true, keep_all: false, filter_pos: &[true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 16, len: 3, tree_name: "__anon_plus_0", transparent: true, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true, false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 16, len: 2, tree_name: "__anon_plus_0", transparent: true, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 16, len: 4, tree_name: "__anon_plus_0", transparent: true, expand1: false, has_alias: false, keep_all: false, filter_pos: &[false, true, true, false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 16, len: 3, tree_name: "__anon_plus_0", transparent: true, expand1: false, has_alias: false, keep_all: false, filter_pos: &[false, true, false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 17, len: 5, tree_name: "array", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true, false, false, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 17, len: 4, tree_name: "array", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true, false, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 17, len: 3, tree_name: "array", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 17, len: 4, tree_name: "array", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, false, false, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 17, len: 3, tree_name: "array", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, false, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 17, len: 2, tree_name: "array", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 18, len: 3, tree_name: "__anon_plus_1", transparent: true, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true, false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 18, len: 2, tree_name: "__anon_plus_1", transparent: true, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 18, len: 4, tree_name: "__anon_plus_1", transparent: true, expand1: false, has_alias: false, keep_all: false, filter_pos: &[false, true, true, false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 18, len: 3, tree_name: "__anon_plus_1", transparent: true, expand1: false, has_alias: false, keep_all: false, filter_pos: &[false, true, false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 19, len: 5, tree_name: "object", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true, false, false, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 19, len: 4, tree_name: "object", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true, false, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 19, len: 3, tree_name: "object", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 19, len: 4, tree_name: "object", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, false, false, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 19, len: 3, tree_name: "object", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, false, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 19, len: 2, tree_name: "object", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[true, true], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 20, len: 4, tree_name: "pair", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[false, true, true, false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 21, len: 1, tree_name: "string", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, nones_before: &[], is_start: false },
        RuleData { origin: 13, len: 1, tree_name: "$root_start", transparent: false, expand1: false, has_alias: false, keep_all: false, filter_pos: &[false], placeholder_count: 0, nones_before: &[], is_start: true },
    ],
    action: &[
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5)), (9, Action::Shift(6)), (10, Action::Shift(7))],
        &[(0, Action::Reduce(4)), (8, Action::Reduce(4)), (11, Action::Reduce(4)), (12, Action::Reduce(4))],
        &[(0, Action::Reduce(29)), (7, Action::Reduce(29)), (8, Action::Reduce(29)), (11, Action::Reduce(29)), (12, Action::Reduce(29))],
        &[(0, Action::Reduce(6)), (8, Action::Reduce(6)), (11, Action::Reduce(6)), (12, Action::Reduce(6))],
        &[(0, Action::Reduce(7)), (8, Action::Reduce(7)), (11, Action::Reduce(7)), (12, Action::Reduce(7))],
        &[(0, Action::Reduce(5)), (8, Action::Reduce(5)), (11, Action::Reduce(5)), (12, Action::Reduce(5))],
        &[(2, Action::Shift(2)), (3, Action::Shift(13)), (11, Action::Shift(14))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (3, Action::Shift(17)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5)), (9, Action::Shift(6)), (10, Action::Shift(7)), (12, Action::Shift(18))],
        &[(0, Action::Accept)],
        &[(0, Action::Reduce(0))],
        &[(0, Action::Reduce(2)), (8, Action::Reduce(2)), (11, Action::Reduce(2)), (12, Action::Reduce(2))],
        &[(0, Action::Reduce(1)), (8, Action::Reduce(1)), (11, Action::Reduce(1)), (12, Action::Reduce(1))],
        &[(0, Action::Reduce(3)), (8, Action::Reduce(3)), (11, Action::Reduce(3)), (12, Action::Reduce(3))],
        &[(2, Action::Shift(2)), (11, Action::Shift(20))],
        &[(0, Action::Reduce(27)), (8, Action::Reduce(27)), (11, Action::Reduce(27)), (12, Action::Reduce(27))],
        &[(8, Action::Shift(22)), (11, Action::Shift(23))],
        &[(7, Action::Shift(25))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5)), (9, Action::Shift(6)), (10, Action::Shift(7)), (12, Action::Shift(26))],
        &[(0, Action::Reduce(17)), (8, Action::Reduce(17)), (11, Action::Reduce(17)), (12, Action::Reduce(17))],
        &[(8, Action::Shift(28)), (12, Action::Shift(29))],
        &[(0, Action::Reduce(24)), (8, Action::Reduce(24)), (11, Action::Reduce(24)), (12, Action::Reduce(24))],
        &[(8, Action::Shift(22)), (11, Action::Shift(31))],
        &[(2, Action::Shift(2)), (3, Action::Shift(33))],
        &[(0, Action::Reduce(26)), (8, Action::Reduce(26)), (11, Action::Reduce(26)), (12, Action::Reduce(26))],
        &[(8, Action::Shift(35)), (11, Action::Shift(36))],
        &[(3, Action::Shift(37))],
        &[(0, Action::Reduce(14)), (8, Action::Reduce(14)), (11, Action::Reduce(14)), (12, Action::Reduce(14))],
        &[(8, Action::Shift(28)), (12, Action::Shift(38))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (3, Action::Shift(40)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5)), (9, Action::Shift(6)), (10, Action::Shift(7))],
        &[(0, Action::Reduce(16)), (8, Action::Reduce(16)), (11, Action::Reduce(16)), (12, Action::Reduce(16))],
        &[(8, Action::Shift(42)), (12, Action::Shift(43))],
        &[(0, Action::Reduce(23)), (8, Action::Reduce(23)), (11, Action::Reduce(23)), (12, Action::Reduce(23))],
        &[(8, Action::Shift(35)), (11, Action::Shift(44))],
        &[(2, Action::Shift(2))],
        &[(8, Action::Reduce(19)), (11, Action::Reduce(19))],
        &[(2, Action::Shift(2)), (3, Action::Shift(46))],
        &[(0, Action::Reduce(25)), (8, Action::Reduce(25)), (11, Action::Reduce(25)), (12, Action::Reduce(25))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5)), (9, Action::Shift(6)), (10, Action::Shift(7))],
        &[(0, Action::Reduce(13)), (8, Action::Reduce(13)), (11, Action::Reduce(13)), (12, Action::Reduce(13))],
        &[(8, Action::Shift(42)), (12, Action::Shift(49))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5)), (9, Action::Shift(6)), (10, Action::Shift(7))],
        &[(8, Action::Reduce(9)), (12, Action::Reduce(9))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (3, Action::Shift(51)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5)), (9, Action::Shift(6)), (10, Action::Shift(7))],
        &[(0, Action::Reduce(15)), (8, Action::Reduce(15)), (11, Action::Reduce(15)), (12, Action::Reduce(15))],
        &[(0, Action::Reduce(22)), (8, Action::Reduce(22)), (11, Action::Reduce(22)), (12, Action::Reduce(22))],
        &[(8, Action::Reduce(18)), (11, Action::Reduce(18))],
        &[(2, Action::Shift(2))],
        &[(8, Action::Reduce(21)), (11, Action::Reduce(21))],
        &[(8, Action::Reduce(28)), (11, Action::Reduce(28))],
        &[(0, Action::Reduce(12)), (8, Action::Reduce(12)), (11, Action::Reduce(12)), (12, Action::Reduce(12))],
        &[(8, Action::Reduce(8)), (12, Action::Reduce(8))],
        &[(1, Action::Shift(1)), (2, Action::Shift(2)), (4, Action::Shift(3)), (5, Action::Shift(4)), (6, Action::Shift(5)), (9, Action::Shift(6)), (10, Action::Shift(7))],
        &[(8, Action::Reduce(11)), (12, Action::Reduce(11))],
        &[(8, Action::Reduce(20)), (11, Action::Reduce(20))],
        &[(8, Action::Reduce(10)), (12, Action::Reduce(10))],
    ],
    goto: &[
        &[(1, 8), (2, 9), (4, 10), (6, 11), (8, 12)],
        &[],
        &[],
        &[],
        &[],
        &[],
        &[(7, 15), (8, 16)],
        &[(2, 19), (4, 10), (6, 11), (8, 12)],
        &[],
        &[],
        &[],
        &[],
        &[],
        &[(7, 21), (8, 16)],
        &[],
        &[(5, 24)],
        &[],
        &[(2, 27), (4, 10), (6, 11), (8, 12)],
        &[],
        &[(3, 30)],
        &[],
        &[(5, 32)],
        &[(7, 34), (8, 16)],
        &[],
        &[],
        &[],
        &[],
        &[(3, 39)],
        &[(2, 41), (4, 10), (6, 11), (8, 12)],
        &[],
        &[],
        &[],
        &[],
        &[(7, 45), (8, 16)],
        &[],
        &[(7, 47), (8, 16)],
        &[],
        &[(2, 48), (4, 10), (6, 11), (8, 12)],
        &[],
        &[],
        &[(2, 50), (4, 10), (6, 11), (8, 12)],
        &[],
        &[(2, 52), (4, 10), (6, 11), (8, 12)],
        &[],
        &[],
        &[],
        &[(7, 53), (8, 16)],
        &[],
        &[],
        &[],
        &[],
        &[(2, 54), (4, 10), (6, 11), (8, 12)],
        &[],
        &[],
        &[],
    ],
    start_states: &[("start", 0)],
    start_default: "start",
    global_prefix: "",
    scan_groups: &[
        (1, "(?:\\+|\\-)?(?:(?:(?:(?:(?:(?:(?:[0-9]))+)(?:(?:e|E)(?:(?:\\+|\\-)?(?:(?:(?:[0-9]))+))))|(?:(?:(?:(?:(?:(?:[0-9]))+)\\.(?:(?:(?:(?:[0-9]))+))?)|(?:\\.(?:(?:(?:[0-9]))+)))(?:(?:(?:e|E)(?:(?:\\+|\\-)?(?:(?:(?:[0-9]))+))))?)))|(?:(?:(?:(?:[0-9]))+)))"),
        (2, "\"(?:(?:(?:[^\"\\\\\\n]|\\\\.))*)\""),
        (3, "(?:[ \\t\\f\\r\\n])+"),
        (4, "false"),
        (5, "null"),
        (6, "true"),
        (7, ":"),
        (8, ","),
        (9, "\\{"),
        (10, "\\["),
        (11, "\\}"),
        (12, "\\]"),
    ],
    unless: &[
    ],
    ignore: &[],
    propagate_positions: false,
};

impl Parser {
    /// Construct the parser for this baked grammar.
    pub fn new() -> Parser {
        Parser::from_data(&DATA)
    }
}

impl Default for Parser {
    fn default() -> Self {
        Parser::new()
    }
}
}

#[allow(unused_imports)]
pub use parser::{Child, ParseTree, Parser, Token, Tree};
