mod common;

use std::path::Path;

/// Run the JSON grammar against every file in the JSONTestSuite corpus.
///
/// We use the Python-Lark oracle (generated by generate_oracles.py) as the
/// reference. Where Python Lark has a definitive pass/fail result, our parser
/// must agree. Grammar limitations that affect Python Lark equally are skipped.
#[test]
fn test_json_corpus_against_oracle() {
    let corpus_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/corpora/JSONTestSuite/test_parsing");

    if !corpus_dir.exists() {
        eprintln!("JSONTestSuite submodule not initialised — skipping corpus test");
        return;
    }

    // Load Python-Lark oracle for cross-checking
    let manifest_oracle = common::load_oracle("json_corpus", "manifest");
    let manifest: std::collections::HashMap<String, bool> = manifest_oracle
        .as_array()
        .unwrap_or(&vec![])
        .iter()
        .map(|entry| {
            let name = entry["file"].as_str().unwrap_or("").to_string();
            let ok = entry["python_lark_ok"].as_bool().unwrap_or(false);
            (name, ok)
        })
        .collect();

    let lark = common::make_lalr_from_file("json");

    let mut hard_failures: Vec<String> = Vec::new();
    let mut agree = 0usize;
    let mut total_definitive = 0usize;

    let mut entries: Vec<_> = std::fs::read_dir(&corpus_dir)
        .expect("Cannot read corpus directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |x| x == "json"))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        let fname = entry.file_name().to_string_lossy().to_string();

        let text = match std::fs::read_to_string(&path) {
            Ok(t) => t,
            Err(e) => {
                eprintln!("SKIP {fname}: cannot read: {e}");
                continue;
            }
        };

        let parse_ok = lark.parse(&text).is_ok();

        // Only check files where Python Lark has a definitive result
        let python_ok = match manifest.get(&fname) {
            Some(&v) => v,
            None => continue,
        };
        total_definitive += 1;

        if parse_ok == python_ok {
            agree += 1;
        } else {
            hard_failures.push(format!(
                "FAIL {fname}: Rust={parse_ok} Python={python_ok}"
            ));
        }
    }

    let pct = if total_definitive > 0 {
        (agree * 100) / total_definitive
    } else {
        100
    };
    eprintln!(
        "JSONTestSuite oracle agreement: {agree}/{total_definitive} ({pct}%)"
    );

    if !hard_failures.is_empty() {
        panic!(
            "JSONTestSuite oracle mismatches ({}):\n{}",
            hard_failures.len(),
            hard_failures.join("\n")
        );
    }
}
