//! Lookaround behavioral oracles — the engine-agnostic gate for the lookaround
//! strategy (`docs/LOOKAROUND_ELIMINATION_PLAN.md`, rationale in
//! `docs/LOOKAROUND_STRATEGY_ANALYSIS.md`).
//!
//! The strategy retires `fancy-regex` by *eliminating* every bounded lookaround
//! terminal at grammar-load time — rewriting it to a lookaround-free regex that runs
//! on the linear `regex` engine — and rejecting anything that cannot be lowered. These
//! oracles pin the exact lexing semantics that rewrite must reproduce. Crucially they
//! **pass against today's `fancy-regex` lexer** — so committing them now locks the
//! behavior, and the rewrite cannot silently diverge. (They are independent of *how*
//! the behavior is produced, so they equally gate the now-shelved Pike-VM lowering
//! explored in the closed PR #110.)
//!
//! ## Cross-algorithm matrix (the airtightness requirement)
//!
//! The lookaround terminals do not flow through one lexer — they flow through *three*
//! engines that all route to `fancy-regex` today and that the rewrite must cover
//! together: the combined `Scanner` (basic + contextual lexers), the per-terminal
//! `DynamicMatcher` (Earley dynamic + dynamic_complete), and the `unless` retype.
//! Testing a single combo would leave the others unwatched through the rewrite, so
//! each grammar is replayed under **every (parser, lexer) combo Python Lark allows**
//! (see `_LOOKAROUND_MATRIX` in `generate_oracles.py`): lalr×{contextual,basic},
//! earley×{basic,dynamic,dynamic_complete}, cyk×basic.
//!
//! The oracle records Python Lark's *actual* result per combo, not a single intent —
//! so genuine per-engine differences are pinned, not papered over. For example
//! `dynamic_complete` accepts `"aaa"` for the length-changing `a+(?!b)` grammar
//! (it explores the shorter tokenization `A="a"`) where maximal-munch lexers reject
//! it. The gate is: **lark-rs reproduces Python's result for each combo, byte for
//! byte.**
//!
//! ## The grammar shapes
//!
//!   * `trailing_neg_lookahead` — the **length-changing** case: a greedy `a+` forced
//!     to a *shorter* match by a trailing `(?!b)`.
//!   * `trailing_pos_lookahead` / `leading_pos_lookbehind` — the positive forms.
//!   * `leading_neg_lookbehind` — the even-backslash STRING-guard shape
//!     `(?<!\\)(?:\\\\)*"`, the reversed-body lookbehind adversary.
//!   * `inline_flag_in_assertion` / `global_flag_over_assertion` — a `(?i:…)` inline
//!     flag inside an assertion body, and `g_regex_flags=IGNORECASE` over an
//!     assertion; both must survive the front-end's strip/lower step.
//!
//! Oracle: `fixtures/oracles/lookaround/cases.json` (a list of `{name, grammar,
//! g_regex_flags, combos}` groups, each combo `{parser, lexer, available, cases}`),
//! generated by `tools/generate_oracles.py::generate_lookaround`.

mod common;

use common::{load_oracle, tree_matches_oracle};
use lark_rs::grammar::terminal::flags;
use lark_rs::{Lark, LarkOptions, LexerType, ParserAlgorithm};

/// Map a serialized `g_regex_flags` name (the oracle's strings) to its flag bit —
/// the lockstep counterpart of `_RE_FLAGS` in `generate_oracles.py`.
fn flag_bit(name: &str) -> u32 {
    match name {
        "IGNORECASE" => flags::IGNORECASE,
        "MULTILINE" => flags::MULTILINE,
        "DOTALL" => flags::DOTALL,
        "VERBOSE" => flags::VERBOSE,
        other => panic!("unknown g_regex_flags name in oracle: {other:?}"),
    }
}

/// Map the oracle's `(parser, lexer)` strings to lark-rs enums. The combos mirror
/// `_LOOKAROUND_MATRIX`; an unknown string is a generator/replay drift bug.
fn combo_enums(parser: &str, lexer: &str) -> (ParserAlgorithm, LexerType) {
    let p = match parser {
        "lalr" => ParserAlgorithm::Lalr,
        "earley" => ParserAlgorithm::Earley,
        "cyk" => ParserAlgorithm::Cyk,
        other => panic!("unknown parser in oracle: {other:?}"),
    };
    let l = match lexer {
        "contextual" => LexerType::Contextual,
        "basic" => LexerType::Basic,
        "dynamic" => LexerType::Dynamic,
        "dynamic_complete" => LexerType::DynamicComplete,
        other => panic!("unknown lexer in oracle: {other:?}"),
    };
    (p, l)
}

#[test]
fn test_lookaround_oracle() {
    let oracle = load_oracle("lookaround", "cases");
    let groups = oracle.as_array().expect("oracle must be a list of groups");

    let mut failures = Vec::new();
    let mut checked_combos = 0usize;
    let mut checked_cases = 0usize;

    for group in groups {
        let name = group["name"].as_str().expect("group needs a name");
        let grammar = group["grammar"].as_str().expect("group needs a grammar");

        let g_regex_flags = group["g_regex_flags"]
            .as_array()
            .map(|a| {
                a.iter()
                    .fold(0u32, |acc, v| acc | flag_bit(v.as_str().unwrap()))
            })
            .unwrap_or(0);

        for combo in group["combos"].as_array().expect("group needs combos") {
            // Python could not build this combo for this grammar — the oracle
            // defines no behavior to check, so skip it (rather than assert against
            // a behavior that doesn't exist).
            if !combo["available"].as_bool().unwrap_or(false) {
                continue;
            }
            let parser = combo["parser"].as_str().unwrap();
            let lexer = combo["lexer"].as_str().unwrap();
            let (algo, lexer_ty) = combo_enums(parser, lexer);
            let tag = format!("{name} [{parser}/{lexer}]");

            // Python built this combo, so lark-rs must too; a build failure here is a
            // real parity divergence, not a skip.
            let lark = match Lark::new(
                grammar,
                LarkOptions {
                    parser: algo,
                    lexer: lexer_ty,
                    start: vec!["start".to_string()],
                    g_regex_flags,
                    ..Default::default()
                },
            ) {
                Ok(l) => l,
                Err(e) => {
                    failures.push(format!(
                        "{tag}: Python built this combo but lark-rs failed to: {e}"
                    ));
                    continue;
                }
            };
            checked_combos += 1;

            for case in combo["cases"].as_array().expect("combo needs cases") {
                let input = case["input"].as_str().unwrap_or("");
                let oracle_ok = case["ok"].as_bool().unwrap_or(false);
                let result = lark.parse(input);
                checked_cases += 1;

                match (oracle_ok, &result) {
                    (true, Ok(tree)) => {
                        if let Err(msg) = tree_matches_oracle(tree, &case["tree"]) {
                            failures.push(format!("{tag} input={input:?}: tree mismatch: {msg}"));
                        }
                    }
                    (true, Err(e)) => failures.push(format!(
                        "{tag} input={input:?}: Python parsed this, lark-rs errored: {e}"
                    )),
                    (false, Err(_)) => {} // both reject — agreement
                    (false, Ok(_)) => failures.push(format!(
                        "{tag} input={input:?}: Python rejected this, lark-rs accepted it"
                    )),
                }
            }
        }
    }

    assert!(
        checked_combos >= 30,
        "expected the full cross-algorithm matrix (~36 combos), only checked {checked_combos}"
    );

    if !failures.is_empty() {
        panic!(
            "lookaround lowering oracle failures ({} across {checked_combos} combos / \
             {checked_cases} cases):\n{}",
            failures.len(),
            failures.join("\n")
        );
    }
}

// ───────────────────────────────────────────────────────────────────────────
// Milestone E2a — per-terminal match-length equivalence
// ───────────────────────────────────────────────────────────────────────────
//
// The behavioral oracle above (and the stdlib oracle in `test_stdlib.rs`) gate the
// *grammar*. This module proves the individual rewrites at the *terminal* level: it
// runs each ORIGINAL lookaround terminal on `fancy-regex` and its lookaround-free
// REWRITE on the `regex` crate, then asserts the two anchored matched-prefix
// functions (the length of the prefix matched starting at offset 0, or "no match")
// agree over a generated corpus. Both terminals are regular, so this is the decidable
// equivalence the plan calls for (docs/LOOKAROUND_ELIMINATION_PLAN.md §E2). The two
// engines are leftmost-first/backtracking like Python `re`, and the Python-generated
// oracles independently cross-check each side, so the proof is triangulated.
//
// The terminals proven here are exactly milestone E2a's scope: python `STRING` /
// `LONG_STRING` and the classic block-comment shape.
mod matchlen {
    use fancy_regex::Regex as Fancy;
    use regex::Regex;

    // --- The originals (lookaround). Flags mirror the bundled `python.lark`:
    //     STRING is `/…/i`, LONG_STRING is `/…/is`. `^` anchors the prefix match. ---
    const STRING_ORIG: &str =
        r#"(?i)^(?:([ubf]?r?|r[ubf])("(?!"").*?(?<!\\)(\\\\)*?"|'(?!'').*?(?<!\\)(\\\\)*?'))"#;
    const LONG_ORIG: &str =
        r#"(?is)^(?:([ubf]?r?|r[ubf])(""".*?(?<!\\)(\\\\)*?"""|'''.*?(?<!\\)(\\\\)*?'''))"#;
    const COMMENT_ORIG: &str = r#"^(?:/\*(\*(?!/)|[^*])*\*/)"#;

    // --- The lookaround-free rewrites (what the bundled grammar now ships, and what
    //     E2/E5 would emit for the block-comment idiom). ---
    const STRING_NEW: &str =
        r#"(?i)^(?:([ubf]?r?|r[ubf])("(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'))"#;
    const LONG_NEW: &str =
        r#"(?is)^(?:([ubf]?r?|r[ubf])("""(?:[^\\]|\\.)*?"""|'''(?:[^\\]|\\.)*?'''))"#;
    const COMMENT_NEW: &str = r#"^(?:/\*(?:[^*]|\*+[^*/])*\*+/)"#;

    /// Anchored matched-prefix length of an original (lookaround) terminal at the
    /// start of `s`, or `None`. `^` keeps it to offset 0.
    fn fancy_prefix(re: &Fancy, s: &str) -> Option<usize> {
        match re.find(s) {
            Ok(Some(m)) if m.start() == 0 => Some(m.end()),
            _ => None,
        }
    }

    /// Same matched-prefix function for a lookaround-free rewrite on the `regex` crate.
    fn regex_prefix(re: &Regex, s: &str) -> Option<usize> {
        re.find(s).filter(|m| m.start() == 0).map(|m| m.end())
    }

    /// Every string over `alphabet` of length `0..=max_len`.
    fn corpus(alphabet: &[char], max_len: usize) -> Vec<String> {
        let mut all = vec![String::new()];
        let mut frontier = vec![String::new()];
        for _ in 0..max_len {
            let mut next = Vec::with_capacity(frontier.len() * alphabet.len());
            for s in &frontier {
                for &c in alphabet {
                    let mut t = s.clone();
                    t.push(c);
                    next.push(t);
                }
            }
            all.extend_from_slice(&next);
            frontier = next;
        }
        all
    }

    /// `LONG_STRING`: a clean equivalence — no boundary-as-failure, so the original and
    /// the rewrite must agree on the matched-prefix function for *every* corpus string.
    #[test]
    fn long_string_match_length_equivalence() {
        let orig = Fancy::new(LONG_ORIG).unwrap();
        let new = Regex::new(LONG_NEW).unwrap();
        // backslashes (escape pairing), both quote kinds, newlines (DOTALL body), the
        // r/b prefix, and `a` as ordinary content — the axes the lazy escaped body and
        // the even-backslash close turn on.
        let cases = corpus(&['"', '\'', '\\', 'a', '\n', 'r'], 6);
        let mut matched = 0usize;
        for s in &cases {
            let (o, n) = (fancy_prefix(&orig, s), regex_prefix(&new, s));
            assert_eq!(o, n, "LONG_STRING match-length differs on {s:?}");
            matched += o.is_some() as usize;
        }
        assert!(
            matched > 0,
            "corpus must actually exercise some long strings"
        );
    }

    /// The classic block-comment shape (`MULTILINE_COMMENT` idiom). Also a clean
    /// equivalence — full agreement required on every corpus string.
    #[test]
    fn block_comment_match_length_equivalence() {
        let orig = Fancy::new(COMMENT_ORIG).unwrap();
        let new = Regex::new(COMMENT_NEW).unwrap();
        let cases = corpus(&['/', '*', 'a', '\n'], 8);
        let mut matched = 0usize;
        for s in &cases {
            let (o, n) = (fancy_prefix(&orig, s), regex_prefix(&new, s));
            assert_eq!(o, n, "block-comment match-length differs on {s:?}");
            matched += o.is_some() as usize;
        }
        assert!(matched > 0, "corpus must actually exercise some comments");
    }

    /// `STRING` + `LONG_STRING` as the combined string scanner. `LONG_STRING` wins ties
    /// (its `.2` priority), so it is tried first. The original disambiguates the same
    /// pair with `STRING`'s `(?!"")` guard instead — a *trailing-context* boundary with
    /// no lookaround-free per-terminal form. The proof pins two properties:
    ///
    ///   1. **Nothing is lost or changed.** Wherever the original scanner matches, the
    ///      rewrite matches the *same terminal* for the *same length*. (The guarantee
    ///      that matters: no valid token is dropped or retyped.)
    ///   2. **The only divergence is one-directional and tightly bounded.** The rewrite
    ///      additionally accepts an empty short string `""`/`''` (optionally `r`/`b`-
    ///      prefixed) sitting at the head of an over-long quote-run that does not form a
    ///      valid long string (e.g. `""""`). The original rejects these; every one is a
    ///      SyntaxError in CPython, so no valid program differs. The rewrite is a strict
    ///      superset — the reverse divergence never occurs.
    #[test]
    fn string_match_length_equivalence() {
        let s_orig = Fancy::new(STRING_ORIG).unwrap();
        let l_orig = Fancy::new(LONG_ORIG).unwrap();
        let s_new = Regex::new(STRING_NEW).unwrap();
        let l_new = Regex::new(LONG_NEW).unwrap();

        // Combined scanner: LONG_STRING (higher priority) is tried first, then STRING.
        let scan_orig = |s: &str| -> Option<(&'static str, usize)> {
            fancy_prefix(&l_orig, s)
                .map(|n| ("LONG", n))
                .or_else(|| fancy_prefix(&s_orig, s).map(|n| ("STRING", n)))
        };
        let scan_new = |s: &str| -> Option<(&'static str, usize)> {
            regex_prefix(&l_new, s)
                .map(|n| ("LONG", n))
                .or_else(|| regex_prefix(&s_new, s).map(|n| ("STRING", n)))
        };

        let mut cases = corpus(&['"', '\'', '\\', 'a', '\n', 'r', 'b'], 5);
        // The (?!"") boundary lives in adjacent quote-runs; sample them well past the
        // exhaustive length, both bare and with content + a closing quote.
        for q in ['"', '\''] {
            for k in 0..=14 {
                let run: String = std::iter::repeat(q).take(k).collect();
                cases.push(run.clone());
                cases.push(format!("{run}a{q}"));
            }
        }

        let mut preserved = 0usize;
        let mut divergences = 0usize;
        let mut lost_or_changed = Vec::new();
        for s in &cases {
            let (o, n) = (scan_orig(s), scan_new(s));
            if o == n {
                preserved += o.is_some() as usize;
                continue;
            }
            match (o, n) {
                // Property 2: the sole tolerated shape — original matched nothing, the
                // rewrite matched an empty short string at the head of a quote-run.
                (None, Some(("STRING", len))) => {
                    let matched = &s[..len];
                    let q = matched.chars().last().unwrap();
                    let empty_short = matched.ends_with("\"\"") || matched.ends_with("''");
                    let at_quote_run = s[len..].chars().next() == Some(q);
                    assert!(
                        empty_short && at_quote_run,
                        "tolerated STRING divergence must be an empty short string at an \
                         over-long quote-run; got match {matched:?} of {s:?}"
                    );
                    divergences += 1;
                }
                // Property 1 violation: a real bug (a match was dropped or changed).
                _ => lost_or_changed.push((s.clone(), o, n)),
            }
        }

        assert!(
            lost_or_changed.is_empty(),
            "rewrite dropped or changed {} original match(es), e.g. {:?}",
            lost_or_changed.len(),
            &lost_or_changed[..lost_or_changed.len().min(8)]
        );
        assert!(
            preserved > 0,
            "corpus must exercise some real string tokens"
        );
        // The boundary divergence is real and characterized — pin that it is present so
        // a future "fix" that silently changes the carve-out can't pass unnoticed.
        assert!(
            divergences > 0,
            "expected the (?!\"\") trailing-context boundary divergence to be present"
        );
    }
}
