//! Indenter / postlex oracles (Phase 3, issue #41 + #45).
//!
//! A `%declare`d `_INDENT` / `_DEDENT` pair plus the [`Indenter`] postlex hook
//! turns a context-free grammar into a Python-style significant-whitespace one.
//! These tests replay the oracle generated by `tools/generate_oracles.py`
//! (`generate_indenter`, `lexer='basic'`, `postlex=Indenter`) and check lark-rs
//! produces byte-identical trees — and rejects exactly the inputs Python Lark
//! rejects (missing INDENT, bad dedent column, …).

mod common;

use common::{load_oracle, tree_matches_oracle};
use lark_rs::{Ambiguity, Indenter, Lark, LarkOptions, LexerType, ParserAlgorithm};

/// Build a LALR + Indenter parser for a grammar file, with the paren token lists
/// the oracle group recorded.
fn make_indenter(grammar_text: &str, open: Vec<String>, close: Vec<String>) -> Lark {
    Lark::new(
        grammar_text,
        LarkOptions {
            parser: ParserAlgorithm::Lalr,
            lexer: LexerType::Basic,
            start: vec!["start".to_string()],
            postlex: Some(Indenter {
                nl_type: "_NL".to_string(),
                open_paren_types: open,
                close_paren_types: close,
                indent_type: "_INDENT".to_string(),
                dedent_type: "_DEDENT".to_string(),
                tab_len: 8,
            }),
            ..Default::default()
        },
    )
    .unwrap_or_else(|e| panic!("Indenter grammar failed to load: {e}"))
}

fn grammar_text(name: &str) -> String {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/grammars")
        .join(format!("{name}.lark"));
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("Cannot read {}: {e}", path.display()))
}

fn strs(v: &serde_json::Value) -> Vec<String> {
    v.as_array()
        .map(Vec::as_slice)
        .unwrap_or(&[])
        .iter()
        .map(|s| s.as_str().unwrap().to_string())
        .collect()
}

#[test]
fn test_indenter_oracle() {
    let mut checked = 0;
    for name in ["indent", "indent_paren"] {
        let group = load_oracle(name, "cases");
        let lark = make_indenter(
            &grammar_text(name),
            strs(&group["open_paren_types"]),
            strs(&group["close_paren_types"]),
        );

        for case in group["cases"].as_array().unwrap() {
            let input = case["input"].as_str().unwrap();
            let should_parse = case["should_parse"].as_bool().unwrap();
            let oracle_ok = case["ok"].as_bool().unwrap();

            match lark.parse(input) {
                Ok(tree) => {
                    assert!(
                        oracle_ok,
                        "[{name}] {input:?}: lark-rs parsed but Python Lark rejected it"
                    );
                    if let Err(e) = tree_matches_oracle(&tree, &case["tree"]) {
                        panic!("[{name}] {input:?}: tree mismatch: {e}\n got: {tree}");
                    }
                }
                Err(e) => {
                    // We assert *rejection parity* only, not error-message parity:
                    // lark-rs and Python Lark word their errors differently (the
                    // oracle's `error` text is recorded but deliberately not
                    // compared), so a stored message like "Unexpected dedent…" is
                    // documentation, not an assertion target.
                    assert!(
                        !oracle_ok && !should_parse,
                        "[{name}] {input:?}: lark-rs rejected ({e}) but Python Lark accepted it"
                    );
                }
            }
            checked += 1;
        }
    }
    assert!(checked > 0, "no indenter cases were checked");
}

/// A grammar that uses an Indenter terminal it never `%declare`d (here the
/// grammar declares nothing) must fail to build with a clear message, not panic
/// or silently inject untyped tokens.
#[test]
fn test_indenter_requires_declare() {
    let res = Lark::new(
        "start: NAME _NL\nNAME: /[a-z]+/\n_NL: /\\n/\n",
        LarkOptions {
            parser: ParserAlgorithm::Lalr,
            lexer: LexerType::Basic,
            start: vec!["start".to_string()],
            postlex: Some(Indenter {
                nl_type: "_NL".to_string(),
                open_paren_types: vec![],
                close_paren_types: vec![],
                indent_type: "_INDENT".to_string(),
                dedent_type: "_DEDENT".to_string(),
                tab_len: 8,
            }),
            ..Default::default()
        },
    );
    let err = res.err().expect("build should fail without %declare");
    assert!(
        format!("{err}").contains("_INDENT"),
        "error should name the undeclared terminal: {err}"
    );
}

/// A typo'd `nl_type` would make the Indenter a silent no-op (no token ever
/// matches it, so no INDENT/DEDENT is injected and the grammar mis-parses). The
/// build must reject it up front, naming the offending terminal.
#[test]
fn test_indenter_validates_nl_type() {
    let grammar = grammar_text("indent");
    let mut indenter = Indenter {
        nl_type: "_TYPO".to_string(),
        open_paren_types: vec![],
        close_paren_types: vec![],
        indent_type: "_INDENT".to_string(),
        dedent_type: "_DEDENT".to_string(),
        tab_len: 8,
    };
    let build = |ind: Indenter| {
        Lark::new(
            &grammar,
            LarkOptions {
                parser: ParserAlgorithm::Lalr,
                lexer: LexerType::Basic,
                start: vec!["start".to_string()],
                postlex: Some(ind),
                ..Default::default()
            },
        )
    };
    let err = build(indenter.clone())
        .err()
        .expect("build should fail with a typo'd nl_type");
    assert!(
        format!("{err}").contains("_TYPO"),
        "error should name the bad nl_type: {err}"
    );

    // The correct nl_type builds fine.
    indenter.nl_type = "_NL".to_string();
    assert!(build(indenter).is_ok(), "correct nl_type should build");
}

/// postlex rides the LALR frontend only (issue #67); configuring it on another
/// backend must error rather than be silently ignored.
#[test]
fn test_postlex_on_earley_is_rejected() {
    let res = Lark::new(
        &grammar_text("indent"),
        LarkOptions {
            parser: ParserAlgorithm::Earley,
            lexer: LexerType::Basic,
            ambiguity: Ambiguity::Resolve,
            start: vec!["start".to_string()],
            postlex: Some(Indenter {
                nl_type: "_NL".to_string(),
                open_paren_types: vec![],
                close_paren_types: vec![],
                indent_type: "_INDENT".to_string(),
                dedent_type: "_DEDENT".to_string(),
                tab_len: 8,
            }),
            ..Default::default()
        },
    );
    let err = res.err().expect("postlex on Earley should fail to build");
    assert!(
        format!("{err}").contains("lalr"),
        "error should explain LALR-only support: {err}"
    );
}
