//! Phase 2, Sprint 2 — Earley ≡ LALR on unambiguous grammars.
//!
//! The headline exit criterion for the SPPF + forest→tree sprint: `parser='earley'`
//! (basic lexer, `ambiguity='resolve'`) must produce the **same** tree as LALR on
//! every committed *unambiguous* oracle. The oracles were generated by Python Lark
//! (our ground truth), so reusing them here checks Earley against the same trees
//! the LALR engine is held to — proving the new forest walk and the shared
//! `TreeOutputBuilder` agree with the reducer, not just with each other.
//!
//! Ambiguous grammars and `_ambig` forests are covered separately by
//! `test_earley_oracle` (curated) and `test_earley_compliance` (the bank).

mod common;

use common::{load_oracle, make_earley_from_file, replay_oracle_cases};

#[test]
fn test_earley_matches_lalr_oracles() {
    let mut failures = Vec::new();

    // Every unambiguous, *basic-lexable* grammar with a committed oracle. These
    // are the grammars the LALR oracle tests pin. `csv` is deliberately excluded:
    // it relies on the contextual lexer (in `header`, only `WORD` is valid, but a
    // basic lexer picks the higher-priority `NON_SEPARATOR_STRING.2` for a bare
    // letter run). Earley has no parser state to narrow terminals, so it uses the
    // basic lexer — and Python Lark's own earley+basic rejects this grammar with
    // the identical error, so the exclusion tracks Lark, not a lark-rs gap.
    //
    // `terminal_refs` is excluded for the same reason (verified against Python Lark
    // 1.3.1, #268): its only two scanner terminals are `GREETING` (finite max-width
    // 5) and `WORD: LETTER+` (unbounded). Python's basic-lexer terminal sort —
    // `(-priority, -max_width, …)` — therefore puts unbounded `WORD` ahead of
    // `GREETING`, so a leading `"hello"` lexes as `WORD` and `earley+basic` rejects
    // `start: GREETING WORD` with `Unexpected token Token('WORD', 'hello')`. The
    // contextual lexer (LALR) narrows to `GREETING` in the start state and parses
    // it; `earley+dynamic` parses it too. Before #268 lark-rs treated *every* regex
    // as unbounded, so `GREETING` and `WORD` tied and the name-asc tiebreak put
    // `GREETING` first — masking this divergence and *accepting* input Python's
    // earley+basic rejects. Now that finite max-widths are computed, lark-rs matches
    // the oracle's rejection, so this grammar joins the contextual-only set.
    //
    // The replay holds Earley to Python's recorded `ok` via the shared
    // [`common::replay_oracle_cases`] — no silent "Python couldn't parse it either"
    // skip: if Earley ever accepted input Python rejects, it fails loudly.
    for name in ["arithmetic", "json", "keywords"] {
        let lark = make_earley_from_file(name);
        let oracle = load_oracle(name, "cases");
        let cases = oracle.as_array().expect("oracle must be an array");
        failures.extend(replay_oracle_cases(&lark, cases, name, &[]));
    }

    assert!(
        failures.is_empty(),
        "Earley/LALR oracle parity failures:\n{}",
        failures.join("\n")
    );
}
