//! Lookaround lowering oracles — the behavioral gate for the Lexer DFA / B1 plan
//! (`docs/LEXER_DFA_PLAN.md`).
//!
//! The B1 strategy retires `fancy-regex` by *lowering* every bounded lookaround
//! terminal onto the linear `regex` engine (M2), then deleting the backtracking
//! engine entirely (M3). These oracles pin the exact lexing semantics that rewrite
//! must reproduce. Crucially they **pass against today's `fancy-regex` lexer** — so
//! committing them now locks the behavior, and the rewrite cannot silently diverge.
//!
//! ## Cross-algorithm matrix (the airtightness requirement)
//!
//! The lookaround terminals do not flow through one lexer — they flow through *three*
//! engines that all route to `fancy-regex` today and that M2/M3 must rewrite
//! together: the combined `Scanner` (basic + contextual lexers), the per-terminal
//! `DynamicMatcher` (Earley dynamic + dynamic_complete), and the `unless` retype.
//! Testing a single combo would leave the others unwatched through the rewrite, so
//! each grammar is replayed under **every (parser, lexer) combo Python Lark allows**
//! (see `_LOOKAROUND_MATRIX` in `generate_oracles.py`): lalr×{contextual,basic},
//! earley×{basic,dynamic,dynamic_complete}, cyk×basic.
//!
//! The oracle records Python Lark's *actual* result per combo, not a single intent —
//! so genuine per-engine differences are pinned, not papered over. For example
//! `dynamic_complete` accepts `"aaa"` for the length-changing `a+(?!b)` grammar
//! (it explores the shorter tokenization `A="a"`) where maximal-munch lexers reject
//! it. The gate is: **lark-rs reproduces Python's result for each combo, byte for
//! byte.**
//!
//! ## The grammar shapes
//!
//!   * `trailing_neg_lookahead` — the **length-changing** case: a greedy `a+` forced
//!     to a *shorter* match by a trailing `(?!b)`.
//!   * `trailing_pos_lookahead` / `leading_pos_lookbehind` — the positive forms.
//!   * `leading_neg_lookbehind` — the even-backslash STRING-guard shape
//!     `(?<!\\)(?:\\\\)*"`, the reversed-body lookbehind adversary.
//!   * `inline_flag_in_assertion` / `global_flag_over_assertion` — a `(?i:…)` inline
//!     flag inside an assertion body, and `g_regex_flags=IGNORECASE` over an
//!     assertion; both must survive the front-end's strip/lower step.
//!
//! Oracle: `fixtures/oracles/lookaround/cases.json` (a list of `{name, grammar,
//! g_regex_flags, combos}` groups, each combo `{parser, lexer, available, cases}`),
//! generated by `tools/generate_oracles.py::generate_lookaround`.

mod common;

use common::{load_oracle, tree_matches_oracle};
use lark_rs::grammar::terminal::flags;
use lark_rs::{Lark, LarkOptions, LexerType, ParserAlgorithm};

/// Map a serialized `g_regex_flags` name (the oracle's strings) to its flag bit —
/// the lockstep counterpart of `_RE_FLAGS` in `generate_oracles.py`.
fn flag_bit(name: &str) -> u32 {
    match name {
        "IGNORECASE" => flags::IGNORECASE,
        "MULTILINE" => flags::MULTILINE,
        "DOTALL" => flags::DOTALL,
        "VERBOSE" => flags::VERBOSE,
        other => panic!("unknown g_regex_flags name in oracle: {other:?}"),
    }
}

/// Map the oracle's `(parser, lexer)` strings to lark-rs enums. The combos mirror
/// `_LOOKAROUND_MATRIX`; an unknown string is a generator/replay drift bug.
fn combo_enums(parser: &str, lexer: &str) -> (ParserAlgorithm, LexerType) {
    let p = match parser {
        "lalr" => ParserAlgorithm::Lalr,
        "earley" => ParserAlgorithm::Earley,
        "cyk" => ParserAlgorithm::Cyk,
        other => panic!("unknown parser in oracle: {other:?}"),
    };
    let l = match lexer {
        "contextual" => LexerType::Contextual,
        "basic" => LexerType::Basic,
        "dynamic" => LexerType::Dynamic,
        "dynamic_complete" => LexerType::DynamicComplete,
        other => panic!("unknown lexer in oracle: {other:?}"),
    };
    (p, l)
}

#[test]
fn test_lookaround_oracle() {
    let oracle = load_oracle("lookaround", "cases");
    let groups = oracle.as_array().expect("oracle must be a list of groups");

    let mut failures = Vec::new();
    let mut checked_combos = 0usize;
    let mut checked_cases = 0usize;

    for group in groups {
        let name = group["name"].as_str().expect("group needs a name");
        let grammar = group["grammar"].as_str().expect("group needs a grammar");

        let g_regex_flags = group["g_regex_flags"]
            .as_array()
            .map(|a| {
                a.iter()
                    .fold(0u32, |acc, v| acc | flag_bit(v.as_str().unwrap()))
            })
            .unwrap_or(0);

        for combo in group["combos"].as_array().expect("group needs combos") {
            // Python could not build this combo for this grammar — the oracle
            // defines no behavior to check, so skip it (rather than assert against
            // a behavior that doesn't exist).
            if !combo["available"].as_bool().unwrap_or(false) {
                continue;
            }
            let parser = combo["parser"].as_str().unwrap();
            let lexer = combo["lexer"].as_str().unwrap();
            let (algo, lexer_ty) = combo_enums(parser, lexer);
            let tag = format!("{name} [{parser}/{lexer}]");

            // Python built this combo, so lark-rs must too; a build failure here is a
            // real parity divergence, not a skip.
            let lark = match Lark::new(
                grammar,
                LarkOptions {
                    parser: algo,
                    lexer: lexer_ty,
                    start: vec!["start".to_string()],
                    g_regex_flags,
                    ..Default::default()
                },
            ) {
                Ok(l) => l,
                Err(e) => {
                    failures.push(format!(
                        "{tag}: Python built this combo but lark-rs failed to: {e}"
                    ));
                    continue;
                }
            };
            checked_combos += 1;

            for case in combo["cases"].as_array().expect("combo needs cases") {
                let input = case["input"].as_str().unwrap_or("");
                let oracle_ok = case["ok"].as_bool().unwrap_or(false);
                let result = lark.parse(input);
                checked_cases += 1;

                match (oracle_ok, &result) {
                    (true, Ok(tree)) => {
                        if let Err(msg) = tree_matches_oracle(tree, &case["tree"]) {
                            failures.push(format!("{tag} input={input:?}: tree mismatch: {msg}"));
                        }
                    }
                    (true, Err(e)) => failures.push(format!(
                        "{tag} input={input:?}: Python parsed this, lark-rs errored: {e}"
                    )),
                    (false, Err(_)) => {} // both reject — agreement
                    (false, Ok(_)) => failures.push(format!(
                        "{tag} input={input:?}: Python rejected this, lark-rs accepted it"
                    )),
                }
            }
        }
    }

    assert!(
        checked_combos >= 30,
        "expected the full cross-algorithm matrix (~36 combos), only checked {checked_combos}"
    );

    if !failures.is_empty() {
        panic!(
            "lookaround lowering oracle failures ({} across {checked_combos} combos / \
             {checked_cases} cases):\n{}",
            failures.len(),
            failures.join("\n")
        );
    }
}
