//! Grammar standard-library oracle tests (Phase 3, issue #40).
//!
//! Beyond `common.lark`, lark-rs bundles the grammars Python Lark ships under
//! `lark/grammars/` — `python.lark`, `unicode.lark`, and `lark.lark` (the grammar
//! of Lark's own syntax) — under `src/grammars/`, resolvable via the same
//! `%import <lib>.<X>` directive a user writes for `common`. Each bundled file is
//! parsed by lark-rs's *own* loader (never a hand-transcribed table), so these
//! oracles pin that the bundled copy lexes/parses exactly as Python Lark's does and
//! cannot drift.
//!
//! `python.lark` and `lark.lark` carry a few documented lookaround-free adaptations
//! (the Rust `regex` crate has no lookahead/lookbehind — see the header of each
//! bundled file and lark-rs/CLAUDE.md). The cases here exercise the adapted
//! terminals on well-formed input, locking the adaptation against the oracle.
//!
//! Oracle: `fixtures/oracles/stdlib/cases.json` (a list of `{name, grammar,
//! cases}` groups), generated by `tools/generate_oracles.py::generate_stdlib`.

mod common;

use common::{load_oracle, make_lalr, tree_matches_oracle};

#[test]
fn test_stdlib_oracle() {
    let oracle = load_oracle("stdlib", "cases");
    let groups = oracle.as_array().expect("oracle must be a list of groups");

    let mut failures = Vec::new();

    for group in groups {
        let name = group["name"].as_str().expect("group needs a name");
        let grammar = group["grammar"].as_str().expect("group needs a grammar");
        // Build the parser once per group: it imports from a bundled library
        // exactly as a user grammar would.
        let lark = make_lalr(grammar);

        for case in group["cases"].as_array().expect("cases must be an array") {
            let input = case["input"].as_str().unwrap_or("");
            let should_pass = case["should_pass"].as_bool().unwrap_or(false);
            let oracle_ok = case["ok"].as_bool().unwrap_or(false);

            let result = lark.parse(input);

            match (should_pass, oracle_ok, &result) {
                (true, true, Ok(tree)) => {
                    if let Err(msg) = tree_matches_oracle(tree, &case["tree"]) {
                        failures.push(format!("{name} input={input:?}: tree mismatch: {msg}"));
                    }
                }
                (true, true, Err(e)) => {
                    failures.push(format!(
                        "{name} input={input:?}: expected parse success, got error: {e}"
                    ));
                }
                (false, false, Err(_)) => {}
                (false, false, Ok(_)) => {
                    failures.push(format!(
                        "{name} input={input:?}: expected parse failure, but parsing succeeded"
                    ));
                }
                _ => failures.push(format!(
                    "{name} input={input:?}: oracle/expectation disagree (should_pass={should_pass}, oracle_ok={oracle_ok})"
                )),
            }
        }
    }

    if !failures.is_empty() {
        panic!(
            "grammar stdlib oracle failures ({}):\n{}",
            failures.len(),
            failures.join("\n")
        );
    }
}
