//! Phase 2, Sprint 2 — Earley ≡ LALR on unambiguous grammars.
//!
//! The headline exit criterion for the SPPF + forest→tree sprint: `parser='earley'`
//! (basic lexer, `ambiguity='resolve'`) must produce the **same** tree as LALR on
//! every committed *unambiguous* oracle. The oracles were generated by Python Lark
//! (our ground truth), so reusing them here checks Earley against the same trees
//! the LALR engine is held to — proving the new forest walk and the shared
//! `TreeBuilder` agree with the reducer, not just with each other.
//!
//! Ambiguous grammars and `_ambig` forests are covered separately by
//! `test_earley_oracle` (curated) and `test_earley_compliance` (the bank).

mod common;

use common::{load_oracle, make_earley_from_file, tree_matches_oracle};
use lark_rs::Lark;

/// Replay one oracle file (suite/cases.json) through an Earley parser, asserting
/// tree-for-tree agreement on the cases Python Lark accepted, and reject-parity on
/// the rest.
fn check_oracle(lark: &Lark, suite: &str, name: &str) -> Vec<String> {
    let oracle = load_oracle(suite, name);
    let cases = oracle.as_array().expect("oracle must be an array");
    let mut failures = Vec::new();

    for case in cases {
        let input = case["input"].as_str().unwrap_or("");
        let should_pass = case["should_pass"].as_bool().unwrap_or(false);
        let oracle_ok = case["ok"].as_bool().unwrap_or(false);
        let result = lark.parse(input);

        match (should_pass && oracle_ok, &result) {
            (true, Ok(tree)) => {
                if let Err(msg) = tree_matches_oracle(tree, &case["tree"]) {
                    failures.push(format!("[{suite}] input={input:?}: tree mismatch: {msg}"));
                }
            }
            (true, Err(e)) => {
                failures.push(format!(
                    "[{suite}] input={input:?}: expected parse, got: {e}"
                ));
            }
            // Cases Python Lark rejected: Earley must reject them too. (Skip cases
            // Python itself couldn't parse — `should_pass` true but `ok` false.)
            (false, Ok(_)) if !should_pass => {
                failures.push(format!(
                    "[{suite}] input={input:?}: expected parse failure, but it parsed"
                ));
            }
            _ => {}
        }
    }
    failures
}

#[test]
fn test_earley_matches_lalr_oracles() {
    let mut failures = Vec::new();

    // Every unambiguous, *basic-lexable* grammar with a committed oracle. These
    // are the grammars the LALR oracle tests pin. `csv` is deliberately excluded:
    // it relies on the contextual lexer (in `header`, only `WORD` is valid, but a
    // basic lexer picks the higher-priority `NON_SEPARATOR_STRING.2` for a bare
    // letter run). Earley has no parser state to narrow terminals, so it uses the
    // basic lexer — and Python Lark's own earley+basic rejects this grammar with
    // the identical error, so the exclusion tracks Lark, not a lark-rs gap.
    //
    // `terminal_refs` is excluded for the same reason (verified against Python Lark
    // 1.3.1, #268): its only two scanner terminals are `GREETING` (finite max-width
    // 5) and `WORD: LETTER+` (unbounded). Python's basic-lexer terminal sort —
    // `(-priority, -max_width, …)` — therefore puts unbounded `WORD` ahead of
    // `GREETING`, so a leading `"hello"` lexes as `WORD` and `earley+basic` rejects
    // `start: GREETING WORD` with `Unexpected token Token('WORD', 'hello')`. The
    // contextual lexer (LALR) narrows to `GREETING` in the start state and parses
    // it; `earley+dynamic` parses it too. Before #268 lark-rs treated *every* regex
    // as unbounded, so `GREETING` and `WORD` tied and the name-asc tiebreak put
    // `GREETING` first — masking this divergence and *accepting* input Python's
    // earley+basic rejects. Now that finite max-widths are computed, lark-rs matches
    // the oracle's rejection, so this grammar joins the contextual-only set.
    for name in ["arithmetic", "json", "keywords"] {
        let lark = make_earley_from_file(name);
        failures.extend(check_oracle(&lark, name, "cases"));
    }

    assert!(
        failures.is_empty(),
        "Earley/LALR oracle parity failures:\n{}",
        failures.join("\n")
    );
}
