//! `common.lark` terminal-library oracle tests (Phase 3).
//!
//! lark-rs resolves `%import common.X` by parsing its own bundled copy of
//! `common.lark` (`src/grammars/common.lark`) through the same terminal-algebra
//! path it uses for user grammars. These oracles pin that every user-facing common
//! terminal lexes exactly as Python Lark's does, so the bundled copy cannot drift.
//!
//! Oracle: `fixtures/oracles/common/cases.json` (a map of terminal name → cases),
//! generated by `tools/generate_oracles.py::generate_common`.

mod common;

use common::{load_oracle, make_lalr, tree_matches_oracle};

#[test]
fn test_common_terminals_oracle() {
    let oracle = load_oracle("common", "cases");
    let terminals = oracle.as_object().expect("oracle must be a map");

    let mut failures = Vec::new();

    for (name, cases) in terminals {
        // Build a parser whose single token is this common terminal.
        let grammar = format!("start: {name}\n%import common.{name}\n");
        let lark = make_lalr(&grammar);

        for case in cases.as_array().expect("cases must be an array") {
            let input = case["input"].as_str().unwrap_or("");
            let should_pass = case["should_pass"].as_bool().unwrap_or(false);
            let oracle_ok = case["ok"].as_bool().unwrap_or(false);

            let result = lark.parse(input);

            match (should_pass, oracle_ok, &result) {
                (true, true, Ok(tree)) => {
                    if let Err(msg) = tree_matches_oracle(tree, &case["tree"]) {
                        failures.push(format!("{name} input={input:?}: tree mismatch: {msg}"));
                    }
                }
                (true, true, Err(e)) => {
                    failures.push(format!(
                        "{name} input={input:?}: expected parse success, got error: {e}"
                    ));
                }
                (false, false, Err(_)) => {}
                (false, false, Ok(_)) => {
                    failures.push(format!(
                        "{name} input={input:?}: expected parse failure, but parsing succeeded"
                    ));
                }
                _ => failures.push(format!(
                    "{name} input={input:?}: oracle/expectation disagree (should_pass={should_pass}, oracle_ok={oracle_ok})"
                )),
            }
        }
    }

    if !failures.is_empty() {
        panic!(
            "common.lark terminal oracle failures ({}):\n{}",
            failures.len(),
            failures.join("\n")
        );
    }
}
