//! CYK curated oracle tests: replays hand-picked (grammar, input) cases through
//! lark-rs's CYK backend and compares against the Python Lark oracle JSON
//! generated by `tools/generate_oracles.py`.
//!
//! These complement the strip-mined CYK *compliance bank*
//! (`test_cyk_compliance.rs`) with targeted cases the bank misses — in
//! particular `~n` over nullable groups (`(B*)~2`, `(B?)~2`), whose
//! anonymous EBNF helpers are nullable and exercise CYK's nullable-rule
//! carve-out (#186, related to #101).

mod common;

use common::{load_oracle, tree_matches_oracle};
use lark_rs::{Lark, LarkOptions, LexerType, ParserAlgorithm};

fn make_cyk(grammar_text: &str) -> Lark {
    Lark::new(
        grammar_text,
        LarkOptions {
            parser: ParserAlgorithm::Cyk,
            lexer: LexerType::Basic,
            start: vec!["start".to_string()],
            ..Default::default()
        },
    )
    .unwrap_or_else(|e| panic!("CYK grammar failed to load: {e}"))
}

#[test]
fn test_cyk_nullable_group_oracle() {
    let oracle = load_oracle("cyk", "cases");
    let groups = oracle.as_array().expect("oracle must be an array");

    let mut failures = Vec::new();

    for group in groups {
        let name = group["name"].as_str().unwrap_or("<unnamed>");
        let grammar = group["grammar"].as_str().expect("grammar must be a string");
        let cases = group["cases"].as_array().expect("cases must be an array");

        let lark = make_cyk(grammar);

        for (ci, case) in cases.iter().enumerate() {
            let input = case["input"].as_str().unwrap_or("");
            let should_parse = case["should_parse"].as_bool().unwrap_or(false);
            let oracle_ok = case["ok"].as_bool().unwrap_or(false);

            let result = lark.parse(input);

            match (should_parse, oracle_ok, &result) {
                // Case should pass and Python Lark passed: compare trees
                (true, true, Ok(tree)) => {
                    let oracle_tree = &case["tree"];
                    if let Err(msg) = tree_matches_oracle(tree, oracle_tree) {
                        failures.push(format!(
                            "{name}[{ci}] input={input:?}: tree mismatch: {msg}"
                        ));
                    }
                }
                // Case should pass, Python Lark passed, but we failed
                (true, true, Err(e)) => {
                    failures.push(format!(
                        "{name}[{ci}] input={input:?}: expected parse success, got error: {e}"
                    ));
                }
                // Case should fail and we correctly fail
                (false, false, Err(_)) => {}
                // Case should fail and Python Lark failed, but we succeed
                (false, false, Ok(_)) => {
                    failures.push(format!(
                        "{name}[{ci}] input={input:?}: expected parse failure, but parsing succeeded"
                    ));
                }
                // Contradictory: should_parse vs oracle disagree — fail, not skip
                (true, false, _) => {
                    failures.push(format!(
                        "{name}[{ci}] input={input:?}: should_parse=true but oracle says ok=false (contradictory fixture)"
                    ));
                }
                (false, true, _) => {
                    failures.push(format!(
                        "{name}[{ci}] input={input:?}: should_parse=false but oracle says ok=true (contradictory fixture)"
                    ));
                }
            }
        }
    }

    if !failures.is_empty() {
        panic!(
            "CYK nullable-group oracle failures ({} of {}):\n{}",
            failures.len(),
            groups
                .iter()
                .flat_map(|g| g["cases"].as_array())
                .map(|c| c.len())
                .sum::<usize>(),
            failures.join("\n")
        );
    }
}
