/// Transformer oracle fixture schema validation.
///
/// This test loads the committed `tests/fixtures/oracles/transformer/cases.json`
/// generated by `tools/generate_transformer_oracles.py` and validates that every
/// case conforms to the expected schema.  No semantic backend exists yet in
/// lark-rs — this test ensures the fixture format is stable and well-formed so
/// that when a Rust transformer is implemented, it can replay the same action
/// specs and compare results + callback traces.
///
/// See issue #226 (semantic output C1).
mod common;

use serde_json::Value;

/// Load the transformer oracle fixture file.
fn load_transformer_cases() -> Value {
    common::load_oracle("transformer", "cases")
}

// ── Schema validation helpers ───────────────────────────────────────────────

fn assert_is_string(val: &Value, path: &str) {
    assert!(val.is_string(), "{path} must be a string, got {val}");
}

fn assert_is_object(val: &Value, path: &str) {
    assert!(val.is_object(), "{path} must be an object, got {val}");
}

fn assert_is_array(val: &Value, path: &str) {
    assert!(val.is_array(), "{path} must be an array, got {val}");
}

fn assert_is_bool(val: &Value, path: &str) {
    assert!(val.is_boolean(), "{path} must be a boolean, got {val}");
}

fn assert_is_u64(val: &Value, path: &str) {
    assert!(val.is_u64(), "{path} must be a positive integer, got {val}");
}

/// Validate that an action spec is well-formed.
fn validate_action_spec(action: &Value, path: &str) {
    assert_is_object(action, path);
    let obj = action.as_object().unwrap();
    assert!(
        obj.contains_key("action"),
        "{path} must have an 'action' field"
    );
    assert_is_string(&obj["action"], &format!("{path}.action"));

    let action_name = obj["action"].as_str().unwrap();
    let known_actions = [
        "identity",
        "return_value",
        "sum_children",
        "product_children",
        "join_children",
        "concat_children",
        "first_child",
        "int_value",
        "float_value",
        "upper",
        "lower",
        "prefix",
        "discard",
        "wrap_list",
        "wrap_dict",
        "stringify",
    ];
    assert!(
        known_actions.contains(&action_name),
        "{path}.action = {action_name:?} is not a known action type"
    );

    // Validate action-specific required fields.
    match action_name {
        "return_value" | "prefix" => {
            assert!(
                obj.contains_key("value"),
                "{path}: action {action_name:?} requires a 'value' field"
            );
        }
        "join_children" => {
            assert!(
                obj.contains_key("sep"),
                "{path}: action 'join_children' requires a 'sep' field"
            );
            assert_is_string(&obj["sep"], &format!("{path}.sep"));
        }
        "wrap_dict" => {
            assert!(
                obj.contains_key("key"),
                "{path}: action 'wrap_dict' requires a 'key' field"
            );
            assert_is_string(&obj["key"], &format!("{path}.key"));
        }
        _ => {}
    }
}

/// Validate a trace entry.
fn validate_trace_entry(entry: &Value, path: &str) {
    assert_is_object(entry, path);
    let obj = entry.as_object().unwrap();

    assert!(obj.contains_key("kind"), "{path} must have a 'kind' field");
    assert_is_string(&obj["kind"], &format!("{path}.kind"));
    let kind = obj["kind"].as_str().unwrap();
    let known_kinds = ["rule", "token", "default_rule", "default_token"];
    assert!(
        known_kinds.contains(&kind),
        "{path}.kind = {kind:?} is not a known trace kind"
    );

    assert!(obj.contains_key("name"), "{path} must have a 'name' field");
    assert_is_string(&obj["name"], &format!("{path}.name"));
}

/// Validate a config result block (one parser x lexer configuration).
fn validate_config_result(result: &Value, path: &str) {
    assert_is_object(result, path);
    let obj = result.as_object().unwrap();

    assert!(
        obj.contains_key("status"),
        "{path} must have a 'status' field"
    );
    assert_is_string(&obj["status"], &format!("{path}.status"));

    let status = obj["status"].as_str().unwrap();
    match status {
        "ok" => {
            // Must have both value and trace.
            assert!(
                obj.contains_key("value"),
                "{path}: status=ok must have a 'value' field"
            );
            assert!(
                obj.contains_key("trace"),
                "{path}: status=ok must have a 'trace' field"
            );
            assert_is_array(&obj["trace"], &format!("{path}.trace"));

            let trace = obj["trace"].as_array().unwrap();
            for (i, entry) in trace.iter().enumerate() {
                validate_trace_entry(entry, &format!("{path}.trace[{i}]"));
            }
        }
        "build_error" | "parse_error" | "transform_error" => {
            assert!(
                obj.contains_key("error"),
                "{path}: status={status} must have an 'error' field"
            );
            assert_is_string(&obj["error"], &format!("{path}.error"));
        }
        other => {
            panic!("{path}.status = {other:?} is not a known status");
        }
    }
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[test]
fn test_transformer_oracle_schema_valid() {
    let data = load_transformer_cases();

    // Top-level structure.
    assert_is_object(&data, "root");
    let root = data.as_object().unwrap();

    assert!(
        root.contains_key("generator"),
        "root must have a 'generator' field"
    );
    assert_is_string(&root["generator"], "root.generator");

    assert!(
        root.contains_key("schema_version"),
        "root must have a 'schema_version' field"
    );
    assert_is_u64(&root["schema_version"], "root.schema_version");
    assert_eq!(
        root["schema_version"].as_u64().unwrap(),
        1,
        "expected schema_version 1"
    );

    assert!(root.contains_key("cases"), "root must have a 'cases' array");
    assert_is_array(&root["cases"], "root.cases");

    let cases = root["cases"].as_array().unwrap();
    assert!(!cases.is_empty(), "cases array must not be empty");

    // Validate each case.
    let mut names = std::collections::HashSet::new();
    for (i, case) in cases.iter().enumerate() {
        let cp = format!("cases[{i}]");
        assert_is_object(case, &cp);
        let obj = case.as_object().unwrap();

        // Required string fields.
        for field in ["name", "description", "grammar", "input"] {
            assert!(obj.contains_key(field), "{cp} must have a '{field}' field");
            assert_is_string(&obj[field], &format!("{cp}.{field}"));
        }

        // Name uniqueness.
        let name = obj["name"].as_str().unwrap();
        assert!(
            names.insert(name.to_string()),
            "{cp}: duplicate case name {name:?}"
        );

        // Action specs.
        for field in ["rule_actions", "token_actions"] {
            assert!(obj.contains_key(field), "{cp} must have a '{field}' field");
            assert_is_object(&obj[field], &format!("{cp}.{field}"));
            let actions = obj[field].as_object().unwrap();
            for (action_name, action_spec) in actions {
                validate_action_spec(action_spec, &format!("{cp}.{field}.{action_name}"));
            }
        }

        // Optional default handlers (null or action spec).
        for field in ["default_rule", "default_token"] {
            assert!(
                obj.contains_key(field),
                "{cp} must have a '{field}' field (null or action spec)"
            );
            if !obj[field].is_null() {
                validate_action_spec(&obj[field], &format!("{cp}.{field}"));
            }
        }

        // visit_tokens.
        assert!(
            obj.contains_key("visit_tokens"),
            "{cp} must have a 'visit_tokens' field"
        );
        assert_is_bool(&obj["visit_tokens"], &format!("{cp}.visit_tokens"));

        // parser_options.
        assert!(
            obj.contains_key("parser_options"),
            "{cp} must have a 'parser_options' field"
        );
        assert_is_object(&obj["parser_options"], &format!("{cp}.parser_options"));

        // configs: must have at least one, each is a config result.
        assert!(
            obj.contains_key("configs"),
            "{cp} must have a 'configs' field"
        );
        assert_is_object(&obj["configs"], &format!("{cp}.configs"));
        let configs = obj["configs"].as_object().unwrap();
        assert!(!configs.is_empty(), "{cp}.configs must not be empty");
        for (cfg_key, cfg_val) in configs {
            validate_config_result(cfg_val, &format!("{cp}.configs.{cfg_key}"));
        }
    }
}

#[test]
fn test_transformer_oracle_all_cases_ok() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let configs = case["configs"].as_object().unwrap();
        for (cfg_key, cfg_val) in configs {
            let status = cfg_val["status"].as_str().unwrap();
            assert_eq!(
                status, "ok",
                "case {name}:{cfg_key} has status {status:?}, expected 'ok'"
            );
        }
    }
}

#[test]
fn test_transformer_oracle_has_expected_configs() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();

    let expected_configs = ["lalr_basic", "lalr_contextual"];

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let configs = case["configs"].as_object().unwrap();
        for expected in &expected_configs {
            assert!(
                configs.contains_key(*expected),
                "case {name} is missing config {expected:?}"
            );
        }
    }
}

#[test]
fn test_transformer_oracle_traces_nonempty() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let configs = case["configs"].as_object().unwrap();
        for (cfg_key, cfg_val) in configs {
            if cfg_val["status"].as_str().unwrap() == "ok" {
                let trace = cfg_val["trace"].as_array().unwrap();
                assert!(
                    !trace.is_empty(),
                    "case {name}:{cfg_key} has an empty trace"
                );
            }
        }
    }
}

#[test]
fn test_transformer_oracle_has_required_coverage() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();
    let names: Vec<&str> = cases.iter().map(|c| c["name"].as_str().unwrap()).collect();

    // The issue requires all of these to be covered.
    let required = [
        "arithmetic_eval",
        "json_value_builder",
        "token_normalizer_upper",
        "alias",
        "transparent_rule",
        "expand1",
        "filtered_punctuation",
        "keep_all_tokens",
        "maybe_placeholders_true",
        "maybe_placeholders_false",
        "discard_token",
        "discard_rule",
        "default_rule_handler",
        "default_token_handler",
        "callback_order_trace",
    ];

    for req in &required {
        assert!(
            names.contains(req),
            "required case {req:?} is missing from the fixture"
        );
    }
}

#[test]
fn test_transformer_oracle_action_spec_language_neutral() {
    // Verify that action specs contain only JSON-primitive data — no Python
    // code, no lambda strings, no executable content.  This is the
    // "language-neutral" guarantee from the issue.
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();

    for case in cases {
        let name = case["name"].as_str().unwrap();
        for field in ["rule_actions", "token_actions"] {
            let actions = case[field].as_object().unwrap();
            for (action_name, action_spec) in actions {
                let obj = action_spec.as_object().unwrap();
                // Every key must be a string; every value must be a
                // JSON primitive (string, number, bool, null, array, object).
                // No "code", "lambda", "exec", "eval" keys allowed.
                let forbidden = ["code", "lambda", "exec", "eval", "python"];
                for key in obj.keys() {
                    assert!(
                        !forbidden.contains(&key.as_str()),
                        "case {name}.{field}.{action_name} has forbidden key {key:?} — \
                         action specs must be language-neutral"
                    );
                }
            }
        }
    }
}
