//! Lookaround behavioral oracles — the engine-agnostic gate for the lookaround
//! strategy (`docs/LOOKAROUND_ELIMINATION_PLAN.md`, rationale in
//! `docs/LOOKAROUND_STRATEGY_ANALYSIS.md`).
//!
//! The strategy retires `fancy-regex` by *eliminating* every bounded lookaround
//! terminal at grammar-load time — rewriting it to a lookaround-free regex that runs
//! on the linear `regex` engine — and rejecting anything that cannot be lowered. These
//! oracles pin the exact lexing semantics that rewrite must reproduce. Crucially they
//! **pass against today's `fancy-regex` lexer** — so committing them now locks the
//! behavior, and the rewrite cannot silently diverge. (They are independent of *how*
//! the behavior is produced, so they equally gate the now-shelved Pike-VM lowering
//! explored in the closed PR #110.)
//!
//! ## Cross-algorithm matrix (the airtightness requirement)
//!
//! The lookaround terminals do not flow through one lexer — they flow through *three*
//! engines that all route to `fancy-regex` today and that the rewrite must cover
//! together: the combined `Scanner` (basic + contextual lexers), the per-terminal
//! `DynamicMatcher` (Earley dynamic + dynamic_complete), and the `unless` retype.
//! Testing a single combo would leave the others unwatched through the rewrite, so
//! each grammar is replayed under **every (parser, lexer) combo Python Lark allows**
//! (see `_LOOKAROUND_MATRIX` in `generate_oracles.py`): lalr×{contextual,basic},
//! earley×{basic,dynamic,dynamic_complete}, cyk×basic.
//!
//! The oracle records Python Lark's *actual* result per combo, not a single intent —
//! so genuine per-engine differences are pinned, not papered over. For example
//! `dynamic_complete` accepts `"aaa"` for the length-changing `a+(?!b)` grammar
//! (it explores the shorter tokenization `A="a"`) where maximal-munch lexers reject
//! it. The gate is: **lark-rs reproduces Python's result for each combo, byte for
//! byte.**
//!
//! ## The grammar shapes
//!
//!   * `trailing_neg_lookahead` — the **length-changing** case: a greedy `a+` forced
//!     to a *shorter* match by a trailing `(?!b)`.
//!   * `trailing_pos_lookahead` / `leading_pos_lookbehind` — the positive forms.
//!   * `leading_neg_lookbehind` — the even-backslash STRING-guard shape
//!     `(?<!\\)(?:\\\\)*"`, the reversed-body lookbehind adversary.
//!   * `inline_flag_in_assertion` / `global_flag_over_assertion` — a `(?i:…)` inline
//!     flag inside an assertion body, and `g_regex_flags=IGNORECASE` over an
//!     assertion; both must survive the front-end's strip/lower step.
//!
//! Oracle: `fixtures/oracles/lookaround/cases.json` (a list of `{name, grammar,
//! g_regex_flags, combos}` groups, each combo `{parser, lexer, available, cases}`),
//! generated by `tools/generate_oracles.py::generate_lookaround`.

mod common;

use common::{load_oracle, tree_matches_oracle};
use lark_rs::grammar::terminal::flags;
use lark_rs::{Lark, LarkOptions, LexerType, ParserAlgorithm};

/// Map a serialized `g_regex_flags` name (the oracle's strings) to its flag bit —
/// the lockstep counterpart of `_RE_FLAGS` in `generate_oracles.py`.
fn flag_bit(name: &str) -> u32 {
    match name {
        "IGNORECASE" => flags::IGNORECASE,
        "MULTILINE" => flags::MULTILINE,
        "DOTALL" => flags::DOTALL,
        "VERBOSE" => flags::VERBOSE,
        other => panic!("unknown g_regex_flags name in oracle: {other:?}"),
    }
}

/// Map the oracle's `(parser, lexer)` strings to lark-rs enums. The combos mirror
/// `_LOOKAROUND_MATRIX`; an unknown string is a generator/replay drift bug.
fn combo_enums(parser: &str, lexer: &str) -> (ParserAlgorithm, LexerType) {
    let p = match parser {
        "lalr" => ParserAlgorithm::Lalr,
        "earley" => ParserAlgorithm::Earley,
        "cyk" => ParserAlgorithm::Cyk,
        other => panic!("unknown parser in oracle: {other:?}"),
    };
    let l = match lexer {
        "contextual" => LexerType::Contextual,
        "basic" => LexerType::Basic,
        "dynamic" => LexerType::Dynamic,
        "dynamic_complete" => LexerType::DynamicComplete,
        other => panic!("unknown lexer in oracle: {other:?}"),
    };
    (p, l)
}

#[test]
fn test_lookaround_oracle() {
    let oracle = load_oracle("lookaround", "cases");
    let groups = oracle.as_array().expect("oracle must be a list of groups");

    let mut failures = Vec::new();
    let mut checked_combos = 0usize;
    let mut checked_cases = 0usize;

    for group in groups {
        let name = group["name"].as_str().expect("group needs a name");
        let grammar = group["grammar"].as_str().expect("group needs a grammar");

        let g_regex_flags = group["g_regex_flags"]
            .as_array()
            .map(|a| {
                a.iter()
                    .fold(0u32, |acc, v| acc | flag_bit(v.as_str().unwrap()))
            })
            .unwrap_or(0);

        for combo in group["combos"].as_array().expect("group needs combos") {
            // Python could not build this combo for this grammar — the oracle
            // defines no behavior to check, so skip it (rather than assert against
            // a behavior that doesn't exist).
            if !combo["available"].as_bool().unwrap_or(false) {
                continue;
            }
            let parser = combo["parser"].as_str().unwrap();
            let lexer = combo["lexer"].as_str().unwrap();
            let (algo, lexer_ty) = combo_enums(parser, lexer);
            let tag = format!("{name} [{parser}/{lexer}]");

            // Python built this combo, so lark-rs must too; a build failure here is a
            // real parity divergence, not a skip.
            let lark = match Lark::new(
                grammar,
                LarkOptions {
                    parser: algo,
                    lexer: lexer_ty,
                    start: vec!["start".to_string()],
                    g_regex_flags,
                    ..Default::default()
                },
            ) {
                Ok(l) => l,
                Err(e) => {
                    failures.push(format!(
                        "{tag}: Python built this combo but lark-rs failed to: {e}"
                    ));
                    continue;
                }
            };
            checked_combos += 1;

            for case in combo["cases"].as_array().expect("combo needs cases") {
                let input = case["input"].as_str().unwrap_or("");
                let oracle_ok = case["ok"].as_bool().unwrap_or(false);
                let result = lark.parse(input);
                checked_cases += 1;

                match (oracle_ok, &result) {
                    (true, Ok(tree)) => {
                        if let Err(msg) = tree_matches_oracle(tree, &case["tree"]) {
                            failures.push(format!("{tag} input={input:?}: tree mismatch: {msg}"));
                        }
                    }
                    (true, Err(e)) => failures.push(format!(
                        "{tag} input={input:?}: Python parsed this, lark-rs errored: {e}"
                    )),
                    (false, Err(_)) => {} // both reject — agreement
                    (false, Ok(_)) => failures.push(format!(
                        "{tag} input={input:?}: Python rejected this, lark-rs accepted it"
                    )),
                }
            }
        }
    }

    assert!(
        checked_combos >= 30,
        "expected the full cross-algorithm matrix (~36 combos), only checked {checked_combos}"
    );

    if !failures.is_empty() {
        panic!(
            "lookaround lowering oracle failures ({} across {checked_combos} combos / \
             {checked_cases} cases):\n{}",
            failures.len(),
            failures.join("\n")
        );
    }
}

// ───────────────────────────────────────────────────────────────────────────
// Milestone E2a — per-terminal match-length equivalence
// ───────────────────────────────────────────────────────────────────────────
//
// The behavioral oracle above (and the stdlib oracle in `test_stdlib.rs`) gate the
// *grammar*. This module proves the individual rewrites at the *terminal* level: it
// runs each ORIGINAL lookaround terminal on `fancy-regex` and its lookaround-free
// REWRITE on the `regex` crate, then compares the two anchored matched-prefix
// functions (the length of the prefix matched starting at offset 0, or "no match")
// over a generated corpus. Both terminals are regular, so this is the decidable
// equivalence the plan calls for (docs/LOOKAROUND_ELIMINATION_PLAN.md §E2). The two
// engines are leftmost-first/backtracking like Python `re`, and the Python-generated
// oracles independently cross-check each side, so the proof is triangulated.
//
// E2a changes NO grammar — the bundled files stay verbatim upstream and every string
// terminal stays on `fancy-regex`. This harness only *classifies* the candidates, so
// the eventual E4 rewrite (and any future edit) is gated by a proof, not a guess:
//   * `LONG_STRING` and the classic block-comment shape are **cleanly equivalent** —
//     the rewrites are proven ready (E4 deploys `LONG_STRING`; E2/E5 the block comment),
//     but are not applied to the grammar in this milestone.
//   * `STRING` is a **negative result**: the standard lookaround-free rewrite is *not*
//     equivalent (it accepts `""""`, which the oracle rejects), so `STRING` must stay on
//     its lookaround form. The test pins exactly why, so the conclusion can't rot.
mod matchlen {
    use fancy_regex::Regex as Fancy;
    use regex::Regex;

    // --- The originals (lookaround). Flags mirror the bundled `python.lark`:
    //     STRING is `/…/i`, LONG_STRING is `/…/is`. `^` anchors the prefix match. ---
    const STRING_ORIG: &str =
        r#"(?i)^(?:([ubf]?r?|r[ubf])("(?!"").*?(?<!\\)(\\\\)*?"|'(?!'').*?(?<!\\)(\\\\)*?'))"#;
    const LONG_ORIG: &str =
        r#"(?is)^(?:([ubf]?r?|r[ubf])(""".*?(?<!\\)(\\\\)*?"""|'''.*?(?<!\\)(\\\\)*?'''))"#;
    const COMMENT_ORIG: &str = r#"^(?:/\*(\*(?!/)|[^*])*\*/)"#;

    // --- The lookaround-free rewrites. LONG_STRING / COMMENT are proven-equivalent and
    //     E4-ready (not yet applied to any grammar); STRING_NEW is the *rejected*
    //     candidate kept only to pin why STRING resists elimination. ---
    const STRING_NEW: &str =
        r#"(?i)^(?:([ubf]?r?|r[ubf])("(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'))"#;
    const LONG_NEW: &str =
        r#"(?is)^(?:([ubf]?r?|r[ubf])("""(?:[^\\]|\\.)*?"""|'''(?:[^\\]|\\.)*?'''))"#;
    const COMMENT_NEW: &str = r#"^(?:/\*(?:[^*]|\*+[^*/])*\*+/)"#;

    /// Anchored matched-prefix length of an original (lookaround) terminal at the
    /// start of `s`, or `None`. `^` keeps it to offset 0.
    fn fancy_prefix(re: &Fancy, s: &str) -> Option<usize> {
        match re.find(s) {
            Ok(Some(m)) if m.start() == 0 => Some(m.end()),
            _ => None,
        }
    }

    /// Same matched-prefix function for a lookaround-free rewrite on the `regex` crate.
    fn regex_prefix(re: &Regex, s: &str) -> Option<usize> {
        re.find(s).filter(|m| m.start() == 0).map(|m| m.end())
    }

    /// Every string over `alphabet` of length `0..=max_len`.
    fn corpus(alphabet: &[char], max_len: usize) -> Vec<String> {
        let mut all = vec![String::new()];
        let mut frontier = vec![String::new()];
        for _ in 0..max_len {
            let mut next = Vec::with_capacity(frontier.len() * alphabet.len());
            for s in &frontier {
                for &c in alphabet {
                    let mut t = s.clone();
                    t.push(c);
                    next.push(t);
                }
            }
            all.extend_from_slice(&next);
            frontier = next;
        }
        all
    }

    /// `LONG_STRING`: a clean equivalence — no boundary-as-failure, so the original and
    /// the rewrite must agree on the matched-prefix function for *every* corpus string.
    #[test]
    fn long_string_match_length_equivalence() {
        let orig = Fancy::new(LONG_ORIG).unwrap();
        let new = Regex::new(LONG_NEW).unwrap();
        // backslashes (escape pairing), both quote kinds, newlines (DOTALL body), the
        // r/b prefix, and `a` as ordinary content — the axes the lazy escaped body and
        // the even-backslash close turn on.
        let cases = corpus(&['"', '\'', '\\', 'a', '\n', 'r'], 6);
        let mut matched = 0usize;
        for s in &cases {
            let (o, n) = (fancy_prefix(&orig, s), regex_prefix(&new, s));
            assert_eq!(o, n, "LONG_STRING match-length differs on {s:?}");
            matched += o.is_some() as usize;
        }
        assert!(
            matched > 0,
            "corpus must actually exercise some long strings"
        );
    }

    /// The classic block-comment shape (`MULTILINE_COMMENT` idiom). Also a clean
    /// equivalence — full agreement required on every corpus string.
    #[test]
    fn block_comment_match_length_equivalence() {
        let orig = Fancy::new(COMMENT_ORIG).unwrap();
        let new = Regex::new(COMMENT_NEW).unwrap();
        let cases = corpus(&['/', '*', 'a', '\n'], 8);
        let mut matched = 0usize;
        for s in &cases {
            let (o, n) = (fancy_prefix(&orig, s), regex_prefix(&new, s));
            assert_eq!(o, n, "block-comment match-length differs on {s:?}");
            matched += o.is_some() as usize;
        }
        assert!(matched > 0, "corpus must actually exercise some comments");
    }

    /// **Negative result: `STRING` cannot be eliminated.** This pins *why* `STRING`
    /// keeps its lookaround form while `LONG_STRING` does not. Upstream disambiguates
    /// the short/long pair with `STRING`'s `(?!"")` opening guard — a *trailing-context*
    /// boundary: it makes `""""` a lex error but `"" ""` (two empty strings) valid, a
    /// distinction that lives only at lex time (after `%ignore` drops the whitespace,
    /// both are `STRING STRING` to the parser). The standard lookaround-free rewrite
    /// `("(?:[^"\\\n]|\\.)*"|…)` has no way to express that, so it accepts `""""`, which
    /// the oracle rejects. The test runs the combined short+long scanner both ways and
    /// asserts the divergence is *exactly* that shape — present, and one-directional:
    ///
    ///   1. **No original match is lost or changed** — wherever upstream matches, the
    ///      rewrite matches the same terminal for the same length (the divergence only
    ///      ever *adds* an unwanted match).
    ///   2. **The added matches are all the `""""` shape** — an empty short string at
    ///      the head of an over-long quote-run that is not a valid long string.
    ///
    /// Property 2 (the divergence is non-empty) is the load-bearing assertion: it is the
    /// proof that the rewrite is unacceptable, so the bundled `STRING` is left verbatim.
    #[test]
    fn string_lookaround_free_rewrite_is_not_equivalent() {
        let s_orig = Fancy::new(STRING_ORIG).unwrap();
        let l_orig = Fancy::new(LONG_ORIG).unwrap();
        let s_new = Regex::new(STRING_NEW).unwrap();
        let l_new = Regex::new(LONG_NEW).unwrap();

        // The combined string scanner, long-string first (as the grammar orders it).
        let scan_orig = |s: &str| -> Option<(&'static str, usize)> {
            fancy_prefix(&l_orig, s)
                .map(|n| ("LONG", n))
                .or_else(|| fancy_prefix(&s_orig, s).map(|n| ("STRING", n)))
        };
        let scan_new = |s: &str| -> Option<(&'static str, usize)> {
            regex_prefix(&l_new, s)
                .map(|n| ("LONG", n))
                .or_else(|| regex_prefix(&s_new, s).map(|n| ("STRING", n)))
        };

        let mut cases = corpus(&['"', '\'', '\\', 'a', '\n', 'r', 'b'], 5);
        // The (?!"") boundary lives in adjacent quote-runs; sample them well past the
        // exhaustive length, both bare and with content + a closing quote.
        for q in ['"', '\''] {
            for k in 0..=14 {
                let run: String = std::iter::repeat(q).take(k).collect();
                cases.push(run.clone());
                cases.push(format!("{run}a{q}"));
            }
        }

        let mut preserved = 0usize;
        let mut divergences = 0usize;
        let mut lost_or_changed = Vec::new();
        for s in &cases {
            let (o, n) = (scan_orig(s), scan_new(s));
            if o == n {
                preserved += o.is_some() as usize;
                continue;
            }
            match (o, n) {
                // The sole divergence shape: original matched nothing, the rewrite
                // matched an empty short string at the head of a quote-run (the `""""`).
                (None, Some(("STRING", len))) => {
                    let matched = &s[..len];
                    let q = matched.chars().last().unwrap();
                    let empty_short = matched.ends_with("\"\"") || matched.ends_with("''");
                    let at_quote_run = s[len..].chars().next() == Some(q);
                    assert!(
                        empty_short && at_quote_run,
                        "STRING divergence must be an empty short string at an over-long \
                         quote-run; got match {matched:?} of {s:?}"
                    );
                    divergences += 1;
                }
                // A *changed/dropped* match would be a different, worse failure mode —
                // the rewrite is at least a clean superset, never lossy.
                _ => lost_or_changed.push((s.clone(), o, n)),
            }
        }

        assert!(
            lost_or_changed.is_empty(),
            "rewrite dropped or changed {} original match(es), e.g. {:?}",
            lost_or_changed.len(),
            &lost_or_changed[..lost_or_changed.len().min(8)]
        );
        assert!(
            preserved > 0,
            "corpus must exercise some real string tokens"
        );
        // The load-bearing assertion: the rewrite IS inequivalent (it accepts `""""`),
        // which is exactly why the bundled STRING is not rewritten. If this ever stops
        // holding, STRING has become eliminable and this decision should be revisited.
        assert!(
            divergences > 0,
            "expected the lookaround-free STRING rewrite to diverge (accept `\"\"\"\"`)"
        );
    }

    // ───────────────────────────────────────────────────────────────────────
    // Terminal-reduction diagnosis (follow-up to PR #112) — the three E2
    // candidates the plan still lists as "to be verified": lark's `REGEXP` and
    // `OP`, and python's `DEC_NUMBER` (`docs/TERMINAL_REDUCTION_DIAGNOSIS.md`).
    //
    // The point is to classify each at the *terminal* level (the decidable,
    // oracle-free matched-prefix question) so the engine-scope decision rests on
    // proof, not assertion:
    //   * `REGEXP` is **regex-rewritable** (Type A) — the `(?!\/)` only forbade an
    //     empty `//`, recovered by requiring a non-empty body. Full equivalence.
    //   * `OP` and `DEC_NUMBER` are **boundary-as-failure** (Type C) at the
    //     terminal level — like `STRING`, no lookaround-free regex reproduces the
    //     matched-prefix function (the rewrite only ever *adds* an unwanted
    //     match). Whether that terminal-level gap survives to an end-to-end
    //     accept/reject divergence is a *grammar*-level question taken up in the
    //     diagnosis doc; the harness pins only the decidable terminal fact.
    // ───────────────────────────────────────────────────────────────────────

    // lark's `REGEXP: /\/(?!\/)(\\\/|\\\\|[^\/])*?\/[imslux]*/`. The candidate
    // drops `(?!\/)` and requires a non-empty body (`+`): the body alternation
    // can never start with a bare `/`, so `//` (the only empty-body case the
    // guard blocked) still cannot match, and lazy `*?`/greedy `+` coincide once
    // the body cannot eat the closing `/`.
    const REGEXP_ORIG: &str = r#"^(?:\/(?!\/)(\\\/|\\\\|[^\/])*?\/[imslux]*)"#;
    const REGEXP_NEW: &str = r#"^(?:\/(\\\/|\\\\|[^\/])+\/[imslux]*)"#;

    // lark's `OP: /[+*]|[?](?![a-z])/` and python's leading-zero `DEC_NUMBER`
    // alternative `"0" ("_"? "0")* /(?![1-9])/`, paired with the naive
    // guard-dropping rewrite (kept only to pin *why* each resists a regex form).
    const OP_ORIG: &str = r#"^(?:[+*]|[?](?![a-z]))"#;
    const OP_NEW: &str = r#"^(?:[+*]|[?])"#;
    const DEC_ORIG: &str = r#"^(?:[1-9](_?[0-9])*|0(_?0)*(?![1-9]))"#;
    const DEC_NEW: &str = r#"^(?:[1-9](_?[0-9])*|0(_?0)*)"#;

    /// `REGEXP`: a clean Type-A equivalence — original and rewrite must agree on
    /// the matched-prefix function for every corpus string (the `(?!\/)` is pure
    /// redundancy once the body is required non-empty).
    #[test]
    fn regexp_match_length_equivalence() {
        let orig = Fancy::new(REGEXP_ORIG).unwrap();
        let new = Regex::new(REGEXP_NEW).unwrap();
        // slash (open/close + the `//` boundary), backslash (escape pairing),
        // `a` as body, `i` as a trailing flag.
        let cases = corpus(&['/', '\\', 'a', 'i'], 6);
        let mut matched = 0usize;
        for s in &cases {
            let (o, n) = (fancy_prefix(&orig, s), regex_prefix(&new, s));
            assert_eq!(o, n, "REGEXP match-length differs on {s:?}");
            matched += o.is_some() as usize;
        }
        assert!(matched > 0, "corpus must actually exercise some regexps");
    }

    /// `OP`: a Type-C negative result. `[?](?![a-z])` turns a *successful* `?`
    /// match into a *failure* when a lowercase letter follows — a property a
    /// regex match-length function (which cannot see past its own end) has no way
    /// to express. The divergence is therefore real, and exactly one shape:
    /// original matched nothing, the rewrite matched `?` at the head of `?[a-z]`.
    /// One-directional — the rewrite never drops or changes an original match.
    #[test]
    fn op_lookaround_free_rewrite_is_not_equivalent() {
        let orig = Fancy::new(OP_ORIG).unwrap();
        let new = Regex::new(OP_NEW).unwrap();
        // `+ * ?` are the operators; lowercase / non-lowercase decide the guard.
        let cases = corpus(&['+', '*', '?', 'a', 'Z', '_'], 3);

        let mut preserved = 0usize;
        let mut divergences = 0usize;
        let mut lost_or_changed = Vec::new();
        for s in &cases {
            let (o, n) = (fancy_prefix(&orig, s), regex_prefix(&new, s));
            if o == n {
                preserved += o.is_some() as usize;
                continue;
            }
            match (o, n) {
                (None, Some(1)) => {
                    let next = s[1..].chars().next();
                    assert!(
                        s.starts_with('?') && next.is_some_and(|c| c.is_ascii_lowercase()),
                        "OP divergence must be `?` before a lowercase letter; got {s:?}"
                    );
                    divergences += 1;
                }
                _ => lost_or_changed.push((s.clone(), o, n)),
            }
        }
        assert!(
            lost_or_changed.is_empty(),
            "rewrite dropped or changed {} original OP match(es), e.g. {:?}",
            lost_or_changed.len(),
            &lost_or_changed[..lost_or_changed.len().min(8)]
        );
        assert!(preserved > 0, "corpus must exercise some real OP tokens");
        assert!(
            divergences > 0,
            "expected the guard-free OP rewrite to diverge (match `?` before [a-z])"
        );
    }

    /// `DEC_NUMBER`: a Type-C negative result, but a subtler shape than `STRING`.
    /// `STRING`'s guard is all-or-nothing (`""""` matches *nothing*); here
    /// `(?![1-9])` is **length-changing** — on `001` fancy-regex backtracks the
    /// zero-run to `0` (len 1) so the guard sees a `0` next, while the guard-free
    /// rewrite greedily takes `00` (len 2). That is the `a+(?!b)` trailing-
    /// lookahead family, not a fixed boundary. The harness pins the two
    /// invariants that make it Type-C all the same:
    ///
    ///   1. **One-directional** — the rewrite never matches *less* than the
    ///      original (`new_len >= orig_len` everywhere). The guard only ever
    ///      shortens or blocks, so dropping it only ever lengthens or adds.
    ///   2. **Localized to the guarded alternative** — every divergence is over
    ///      the leading-zero alternative (the original's matched prefix is empty
    ///      or all `0`/`_`); the unguarded `[1-9]…` alternative is byte-identical
    ///      in both. So no lookaround-free regex reproduces the matched-prefix
    ///      function, exactly because the length depends on a *following* digit.
    #[test]
    fn dec_number_lookaround_free_rewrite_is_not_equivalent() {
        let orig = Fancy::new(DEC_ORIG).unwrap();
        let new = Regex::new(DEC_NEW).unwrap();
        // digits across the 0 / 1-9 boundary plus the `_` group separator.
        let cases = corpus(&['0', '1', '9', '_'], 4);

        let mut preserved = 0usize;
        let mut divergences = 0usize;
        let mut shortened = Vec::new();
        for s in &cases {
            let (o, n) = (fancy_prefix(&orig, s), regex_prefix(&new, s));
            let (o_len, n_len) = (o.unwrap_or(0), n.unwrap_or(0));
            // Invariant 1: the rewrite is a superset matcher — never shorter.
            if n_len < o_len {
                shortened.push((s.clone(), o, n));
                continue;
            }
            if o == n {
                preserved += o.is_some() as usize;
                continue;
            }
            // Invariant 2: divergence lives entirely in the leading-zero
            // alternative — the original matched nothing or an all-`0`/`_` run.
            let orig_prefix = &s[..o_len];
            assert!(
                orig_prefix.is_empty() || orig_prefix.bytes().all(|b| b == b'0' || b == b'_'),
                "DEC_NUMBER divergence must be over the leading-zero alternative; \
                 original matched {orig_prefix:?} of {s:?}"
            );
            divergences += 1;
        }
        assert!(
            shortened.is_empty(),
            "rewrite matched *less* than the original on {} case(s), e.g. {:?}",
            shortened.len(),
            &shortened[..shortened.len().min(8)]
        );
        assert!(preserved > 0, "corpus must exercise some real numbers");
        assert!(
            divergences > 0,
            "expected the guard-free DEC_NUMBER rewrite to diverge (over-match a zero-run)"
        );
    }
}

// ───────────────────────────────────────────────────────────────────────────
// Grammar-level recovery (the B-vs-C refinement of the diagnosis)
// ───────────────────────────────────────────────────────────────────────────
//
// The `matchlen` module proves `OP` and `DEC_NUMBER` are *terminal-level*
// irreducible (no lookaround-free regex reproduces their match function). This
// module proves they are nonetheless **grammar-level recoverable**: building the
// grammar with the guard *removed* accepts/rejects exactly the same inputs and
// yields byte-identical trees, because another layer already does the guard's
// job (maximal munch for `OP`; the parser's no-two-adjacent-numbers rule for
// `DEC_NUMBER`). So the eventual E4 rewrite can simply drop these guards — no
// engine primitive, unlike `STRING`.
//
// This is proven here on **lark-rs itself** (guarded routes to `fancy-regex`,
// guard-free to `regex`); the same equivalence was independently confirmed on
// the Python Lark oracle (language + tree equality over the same witnesses), so
// the result is triangulated. `STRING` is the contrast: its guard *does* change
// the language (`""""`), pinned by `test_stdlib.rs`'s end-to-end reject.
mod recovery {
    use super::*;

    /// Parse with both grammars and compare results as `Option<tree>` — `None`
    /// for reject (so two rejects compare equal), `Some(tree)` for accept (so two
    /// accepts must produce identical trees). Returns the per-input verdicts.
    fn compare(guarded: &str, guardfree: &str, corpus: &[&str]) -> Vec<(String, bool, bool)> {
        let g = Lark::new(guarded, LarkOptions::default()).expect("guarded grammar builds");
        let f = Lark::new(guardfree, LarkOptions::default()).expect("guard-free grammar builds");
        // `ParseTree` is not `PartialEq`, so compare structural Debug renderings:
        // `None` for reject (two rejects compare equal), `Some(dump)` for accept
        // (two accepts must produce identical trees).
        let dump = |r: Result<lark_rs::ParseTree, _>| r.ok().map(|t| format!("{t:?}"));
        corpus
            .iter()
            .map(|&s| {
                let (ga, fa) = (dump(g.parse(s)), dump(f.parse(s)));
                assert_eq!(
                    ga, fa,
                    "guarded vs guard-free disagree on {s:?} — guard is NOT grammar-recoverable"
                );
                (s.to_string(), ga.is_some(), fa.is_some())
            })
            .collect()
    }

    /// `OP`'s `(?![a-z])` is redundant with maximal munch: `?foo` lexes as the
    /// longer `RULE` token regardless. Dropping the guard changes nothing.
    #[test]
    fn op_guard_is_grammar_recoverable() {
        const GUARDED: &str = r#"start: (OP | RULE)+
OP: /[+*]|[?](?![a-z])/
RULE: /[?]?[a-z][a-z0-9]*/
%ignore " "
"#;
        let guardfree = GUARDED.replace("[?](?![a-z])", "[?]");
        let verdicts = compare(
            GUARDED,
            &guardfree,
            &["+", "?", "?foo", "?a", "??", "a?b", "*?go"],
        );
        // The guard-sensitive witness must actually be exercised and accepted
        // (so the test is not vacuous): `?foo` is the case the guard guards.
        assert!(
            verdicts.iter().any(|(s, ga, _)| s == "?foo" && *ga),
            "corpus must exercise the maximal-munch case `?foo`"
        );
    }

    /// `DEC_NUMBER`'s `(?![1-9])` is redundant with the parser: without it `0123`
    /// lexes as two number tokens, which no production juxtaposes, so it is a
    /// parse error instead of a lex error — same accept/reject either way.
    #[test]
    fn dec_number_guard_is_grammar_recoverable() {
        const GUARDED: &str = r#"start: NUMBER ("+" NUMBER)*
NUMBER: "1".."9" ("_"? "0".."9")* | "0" ("_"? "0")* /(?![1-9])/
%ignore " "
"#;
        let guardfree = GUARDED.replace(" /(?![1-9])/", "");
        let verdicts = compare(
            GUARDED,
            &guardfree,
            &[
                "0", "00", "123", "0+1", "0123", "007", "10", "0_0", "1_000+0",
            ],
        );
        // The guard-sensitive witness `0123` must be exercised and *rejected* by
        // both — proving the guard is load-bearing at lex time yet recovered.
        assert!(
            verdicts.iter().any(|(s, ga, _)| s == "0123" && !*ga),
            "corpus must exercise the leading-zero case `0123` (rejected both ways)"
        );
    }
}
