/// Transformer oracle: value + trace parity (semantic output C3, issue #228).
///
/// This file does two things:
///
/// 1. **Schema validation** of the committed
///    `tests/fixtures/oracles/transformer/cases.json` (generated by
///    `tools/generate_transformer_oracles.py`, issue #226 / C1) — the fixture
///    format must stay stable and well-formed.
///
/// 2. **The C3 backend gate.** A test-only [`transformer`] module implements
///    `PythonTransformerOracleBuilder` — deliberately *Python-shaped*, not
///    Rust-ergonomic. It holds the action spec keyed by callback-name /
///    terminal-name (exactly the name world `tree_builder::OutputBuilder`'s
///    `build_node(tree_name, …)` / `build_token` seam already speaks), resolves
///    every node it visits to that name world, and emits **both** a final value
///    and an ordered callback trace. For every C1 fixture, the Rust value JSON
///    must equal the Python value JSON **and** the Rust trace must equal the
///    Python trace, across LALR + basic and LALR + contextual.
///
/// The backend is a faithful re-implementation of Python Lark's
/// `Transformer.transform` (a bottom-up post-order walk over the already-shaped
/// parse tree): filtering, `expand1`, transparent-inlining, aliases and
/// `maybe_placeholders` were applied by the engine before the tree was built, so
/// the walk sees exactly the shaped child lists a Python rule method receives.
///
/// RFC §5 — the engine-token vs Python-visible-callback distinction — is honored
/// here: the engine materializes a `Token` value for *every* kept terminal, but a
/// *visible* terminal callback is logged only when the spec defines a method for
/// that terminal (else `__default_token__` if set, else nothing); a kept terminal
/// with no method is materialized as a Token-compatible value **silently**.
/// Naïvely tracing every token is the failure mode this gate exists to catch.
///
/// Scope: LALR + basic and contextual lexer. No Earley/CYK (Python rejects
/// embedded transform there). No public API.
mod common;

use serde_json::Value;

/// Load the transformer oracle fixture file.
fn load_transformer_cases() -> Value {
    common::load_oracle("transformer", "cases")
}

// ── Schema validation helpers ───────────────────────────────────────────────

fn assert_is_string(val: &Value, path: &str) {
    assert!(val.is_string(), "{path} must be a string, got {val}");
}

fn assert_is_object(val: &Value, path: &str) {
    assert!(val.is_object(), "{path} must be an object, got {val}");
}

fn assert_is_array(val: &Value, path: &str) {
    assert!(val.is_array(), "{path} must be an array, got {val}");
}

fn assert_is_bool(val: &Value, path: &str) {
    assert!(val.is_boolean(), "{path} must be a boolean, got {val}");
}

fn assert_is_u64(val: &Value, path: &str) {
    assert!(val.is_u64(), "{path} must be a positive integer, got {val}");
}

/// Validate that an action spec is well-formed.
fn validate_action_spec(action: &Value, path: &str) {
    assert_is_object(action, path);
    let obj = action.as_object().unwrap();
    assert!(
        obj.contains_key("action"),
        "{path} must have an 'action' field"
    );
    assert_is_string(&obj["action"], &format!("{path}.action"));

    let action_name = obj["action"].as_str().unwrap();
    let known_actions = [
        "identity",
        "return_value",
        "sum_children",
        "product_children",
        "join_children",
        "concat_children",
        "first_child",
        "int_value",
        "float_value",
        "upper",
        "lower",
        "prefix",
        "discard",
        "wrap_list",
        "wrap_dict",
        "stringify",
    ];
    assert!(
        known_actions.contains(&action_name),
        "{path}.action = {action_name:?} is not a known action type"
    );

    // Validate action-specific required fields.
    match action_name {
        "return_value" | "prefix" => {
            assert!(
                obj.contains_key("value"),
                "{path}: action {action_name:?} requires a 'value' field"
            );
        }
        "join_children" => {
            assert!(
                obj.contains_key("sep"),
                "{path}: action 'join_children' requires a 'sep' field"
            );
            assert_is_string(&obj["sep"], &format!("{path}.sep"));
        }
        "wrap_dict" => {
            assert!(
                obj.contains_key("key"),
                "{path}: action 'wrap_dict' requires a 'key' field"
            );
            assert_is_string(&obj["key"], &format!("{path}.key"));
        }
        _ => {}
    }
}

/// Validate a trace entry.
fn validate_trace_entry(entry: &Value, path: &str) {
    assert_is_object(entry, path);
    let obj = entry.as_object().unwrap();

    assert!(obj.contains_key("kind"), "{path} must have a 'kind' field");
    assert_is_string(&obj["kind"], &format!("{path}.kind"));
    let kind = obj["kind"].as_str().unwrap();
    let known_kinds = ["rule", "token", "default_rule", "default_token"];
    assert!(
        known_kinds.contains(&kind),
        "{path}.kind = {kind:?} is not a known trace kind"
    );

    assert!(obj.contains_key("name"), "{path} must have a 'name' field");
    assert_is_string(&obj["name"], &format!("{path}.name"));
}

/// Validate a config result block (one parser x lexer configuration).
fn validate_config_result(result: &Value, path: &str) {
    assert_is_object(result, path);
    let obj = result.as_object().unwrap();

    assert!(
        obj.contains_key("status"),
        "{path} must have a 'status' field"
    );
    assert_is_string(&obj["status"], &format!("{path}.status"));

    let status = obj["status"].as_str().unwrap();
    match status {
        "ok" => {
            // Must have both value and trace.
            assert!(
                obj.contains_key("value"),
                "{path}: status=ok must have a 'value' field"
            );
            assert!(
                obj.contains_key("trace"),
                "{path}: status=ok must have a 'trace' field"
            );
            assert_is_array(&obj["trace"], &format!("{path}.trace"));

            let trace = obj["trace"].as_array().unwrap();
            for (i, entry) in trace.iter().enumerate() {
                validate_trace_entry(entry, &format!("{path}.trace[{i}]"));
            }
        }
        "build_error" | "parse_error" | "transform_error" => {
            assert!(
                obj.contains_key("error"),
                "{path}: status={status} must have an 'error' field"
            );
            assert_is_string(&obj["error"], &format!("{path}.error"));
        }
        other => {
            panic!("{path}.status = {other:?} is not a known status");
        }
    }
}

// ── The Python-shaped transformer oracle backend ─────────────────────────────
//
// Deliberately Python-*shaped*: it mirrors `lark.visitors.Transformer.transform`
// rather than presenting a Rust-ergonomic API, because the oracle it must match
// is Python's. It is test-only and touches no public API.
mod transformer {
    use lark_rs::{Child, ParseTree, Token, Tree};
    use serde_json::{json, Map, Value};

    /// A transformed semantic value. Its [`to_json`](TransformValue::to_json)
    /// mirrors the generator's `_serialize_value`, so a Rust value's JSON is
    /// directly comparable to the fixture's Python value JSON.
    #[derive(Clone, Debug)]
    pub enum TransformValue {
        Null,
        Bool(bool),
        Int(i64),
        Float(f64),
        Str(String),
        /// A Token-compatible value (materialized for a kept terminal). Carries
        /// the terminal name + text so it round-trips to the generator's
        /// `{"type":"token", ...}` form.
        Token {
            token_type: String,
            value: String,
        },
        List(Vec<TransformValue>),
        /// A dict; `Vec` keeps the insertion order Python's `dict` preserves.
        Dict(Vec<(String, TransformValue)>),
        Tree {
            data: String,
            children: Vec<TransformValue>,
        },
    }

    impl TransformValue {
        /// Serialize to the same JSON shape `generate_transformer_oracles.py`'s
        /// `_serialize_value` produces, so values compare directly.
        pub fn to_json(&self) -> Value {
            match self {
                TransformValue::Null => Value::Null,
                TransformValue::Bool(b) => json!(b),
                TransformValue::Int(i) => json!(i),
                TransformValue::Float(f) => json!(f),
                TransformValue::Str(s) => json!(s),
                TransformValue::Token { token_type, value } => json!({
                    "type": "token",
                    "token_type": token_type,
                    "value": value,
                }),
                TransformValue::List(items) => {
                    Value::Array(items.iter().map(TransformValue::to_json).collect())
                }
                TransformValue::Dict(entries) => {
                    let mut map = Map::new();
                    for (k, v) in entries {
                        map.insert(k.clone(), v.to_json());
                    }
                    Value::Object(map)
                }
                TransformValue::Tree { data, children } => json!({
                    "type": "tree",
                    "data": data,
                    "children": children.iter().map(TransformValue::to_json).collect::<Vec<_>>(),
                }),
            }
        }

        /// Python's `str(value)` for the values the action specs apply it to
        /// (`join_children` / `concat_children` / `prefix`). Mirrors what CPython
        /// would print for each runtime type the generator can produce.
        fn py_str(&self) -> String {
            match self {
                TransformValue::Null => "None".to_string(),
                TransformValue::Bool(true) => "True".to_string(),
                TransformValue::Bool(false) => "False".to_string(),
                TransformValue::Int(i) => i.to_string(),
                // Python's `str(float)` always renders a decimal point for a
                // finite whole-valued float (`str(3.0) == "3.0"`), where Rust's
                // `Display` would print `3`. Match the common case so a future
                // fixture that joins/concats float children stays faithful.
                TransformValue::Float(f) => py_float_str(*f),
                TransformValue::Str(s) => s.clone(),
                // A Token subclasses str in Python; str(token) is its text.
                TransformValue::Token { value, .. } => value.clone(),
                // list / dict / Tree do not appear inside the str-joining specs
                // in the C1 fixtures; fall back to a debug rendering so a future
                // fixture that does would surface a visible mismatch rather than
                // silently passing.
                other => format!("{other:?}"),
            }
        }
    }

    /// The Discard sentinel — Python Lark's `lark.visitors.Discard`. A token or
    /// rule callback returning it is removed from its parent's child list.
    #[derive(Clone, Debug)]
    enum Maybe {
        Keep(TransformValue),
        Discard,
    }

    /// One callback trace entry, serialized to the fixture's `{kind,name}` shape.
    #[derive(Clone, Debug, PartialEq)]
    pub struct TraceEntry {
        pub kind: String,
        pub name: String,
    }

    impl TraceEntry {
        pub fn to_json(&self) -> Value {
            json!({ "kind": self.kind, "name": self.name })
        }
    }

    /// An action spec, parsed from the language-neutral fixture form. Mirrors the
    /// generator's `_apply_rule_action` / `_apply_token_action`.
    #[derive(Clone, Debug)]
    pub struct Action {
        kind: String,
        value: Option<Value>,
        sep: Option<String>,
        key: Option<String>,
    }

    impl Action {
        pub fn from_json(spec: &Value) -> Action {
            let obj = spec.as_object().expect("action spec must be an object");
            Action {
                kind: obj["action"].as_str().expect("action.kind").to_string(),
                value: obj.get("value").cloned(),
                sep: obj.get("sep").and_then(|v| v.as_str()).map(str::to_string),
                key: obj.get("key").and_then(|v| v.as_str()).map(str::to_string),
            }
        }
    }

    /// Convert a fixture literal (the `"value"` field of `return_value`) into a
    /// [`TransformValue`].
    fn literal(v: &Value) -> TransformValue {
        match v {
            Value::Null => TransformValue::Null,
            Value::Bool(b) => TransformValue::Bool(*b),
            Value::Number(n) => {
                if let Some(i) = n.as_i64() {
                    TransformValue::Int(i)
                } else {
                    TransformValue::Float(n.as_f64().unwrap())
                }
            }
            Value::String(s) => TransformValue::Str(s.clone()),
            Value::Array(a) => TransformValue::List(a.iter().map(literal).collect()),
            Value::Object(o) => {
                TransformValue::Dict(o.iter().map(|(k, v)| (k.clone(), literal(v))).collect())
            }
        }
    }

    /// The deliberately Python-shaped transformer oracle backend.
    ///
    /// It holds the action spec keyed by *callback name* (rule alias / origin —
    /// the `Tree::data` the engine already resolved) and *terminal name*
    /// (`Token::type_`), plus optional `__default__` / `__default_token__`
    /// handlers, exactly as Python's `Transformer` does. `transform` walks the
    /// shaped parse tree bottom-up and records the visible callback trace.
    pub struct PythonTransformerOracleBuilder {
        rule_actions: std::collections::HashMap<String, Action>,
        token_actions: std::collections::HashMap<String, Action>,
        default_rule: Option<Action>,
        default_token: Option<Action>,
        visit_tokens: bool,
        trace: Vec<TraceEntry>,
    }

    impl PythonTransformerOracleBuilder {
        pub fn from_case(case: &Value) -> PythonTransformerOracleBuilder {
            let parse_map = |field: &str| {
                case[field]
                    .as_object()
                    .expect("action map")
                    .iter()
                    .map(|(k, v)| (k.clone(), Action::from_json(v)))
                    .collect()
            };
            let parse_default = |field: &str| {
                let v = &case[field];
                if v.is_null() {
                    None
                } else {
                    Some(Action::from_json(v))
                }
            };
            PythonTransformerOracleBuilder {
                rule_actions: parse_map("rule_actions"),
                token_actions: parse_map("token_actions"),
                default_rule: parse_default("default_rule"),
                default_token: parse_default("default_token"),
                visit_tokens: case["visit_tokens"].as_bool().unwrap_or(true),
                trace: Vec::new(),
            }
        }

        /// Transform a whole parse result, returning the final value and the
        /// ordered callback trace.
        pub fn transform(mut self, tree: &ParseTree) -> (TransformValue, Vec<TraceEntry>) {
            // The root is reached via the same path as any child: a `?start` rule
            // can collapse to a bare token (`ParseTree::Token`), in which case the
            // root value is just that materialized token.
            let value = match self.transform_child_node(&parse_tree_as_child(tree)) {
                Maybe::Keep(v) => v,
                // A start rule never returns Discard in the C1 fixtures; if it
                // ever did, Python would hand back the Discard sentinel, which
                // `_serialize_value` renders as an "unknown" repr. Surface it as
                // Null so the comparison fails loudly rather than panicking.
                Maybe::Discard => TransformValue::Null,
            };
            (value, self.trace)
        }

        /// Transform one child node (a `Child` borrowed from the shaped tree),
        /// returning either a kept value or the Discard sentinel.
        fn transform_child_node(&mut self, child: &Child) -> Maybe {
            match child {
                Child::Tree(t) => self.transform_tree(t),
                Child::Token(tok) => self.transform_token(tok),
                // A `None` placeholder (maybe_placeholders) passes through as a
                // null value with no callback — exactly as Python keeps `None`
                // children without invoking a token handler.
                Child::None => Maybe::Keep(TransformValue::Null),
            }
        }

        /// Transform a rule node: transform its (already-shaped) children
        /// left-to-right, drop Discard results, then dispatch the rule callback.
        fn transform_tree(&mut self, tree: &Tree) -> Maybe {
            let mut children = Vec::new();
            for c in &tree.children {
                if let Maybe::Keep(v) = self.transform_child_node(c) {
                    children.push(v);
                }
            }

            // `tree.data` is the callback name the engine already resolved
            // (alias `-> name`, template source, or origin) — the same name world
            // Python's `create_callback` dispatches on.
            let name = tree.data.clone();
            if let Some(action) = self.rule_actions.get(&name).cloned() {
                self.trace.push(TraceEntry {
                    kind: "rule".to_string(),
                    name: name.clone(),
                });
                apply_rule_action(&action, &name, children)
            } else if let Some(action) = self.default_rule.clone() {
                self.trace.push(TraceEntry {
                    kind: "default_rule".to_string(),
                    name: name.clone(),
                });
                apply_rule_action(&action, &name, children)
            } else {
                // No method and no __default__: Python's default keeps the node as
                // a Tree of the transformed children (Transformer.__default__).
                Maybe::Keep(TransformValue::Tree {
                    data: name,
                    children,
                })
            }
        }

        /// Materialize a shifted terminal. RFC §5: the engine always needs a value,
        /// but a *visible* terminal callback is logged only when the spec defines a
        /// method for that terminal (else `__default_token__` if set), and otherwise
        /// the terminal is materialized as a Token-compatible value **silently**.
        fn transform_token(&mut self, tok: &Token) -> Maybe {
            let token_value = TransformValue::Token {
                token_type: tok.type_.clone(),
                value: tok.value.clone(),
            };

            // __visit_tokens__ == False: tokens never get a callback; they pass
            // through as plain tokens.
            if !self.visit_tokens {
                return Maybe::Keep(token_value);
            }

            if let Some(action) = self.token_actions.get(&tok.type_).cloned() {
                self.trace.push(TraceEntry {
                    kind: "token".to_string(),
                    name: tok.type_.clone(),
                });
                apply_token_action(&action, tok)
            } else if let Some(action) = self.default_token.clone() {
                self.trace.push(TraceEntry {
                    kind: "default_token".to_string(),
                    name: tok.type_.clone(),
                });
                apply_token_action(&action, tok)
            } else {
                // Engine token materialization with no visible callback.
                Maybe::Keep(token_value)
            }
        }
    }

    /// View a [`ParseTree`] as a [`Child`] so the root and inner nodes share one
    /// transform path. Clones are cheap relative to the parse itself and keep the
    /// walk borrow-simple.
    fn parse_tree_as_child(tree: &ParseTree) -> Child {
        match tree {
            ParseTree::Tree(t) => Child::Tree(t.clone()),
            ParseTree::Token(tok) => Child::Token(tok.clone()),
        }
    }

    /// Mirror of the generator's `_apply_rule_action`.
    fn apply_rule_action(action: &Action, data: &str, children: Vec<TransformValue>) -> Maybe {
        match action.kind.as_str() {
            "identity" => Maybe::Keep(TransformValue::Tree {
                data: data.to_string(),
                children,
            }),
            "return_value" => Maybe::Keep(literal(
                action.value.as_ref().expect("return_value needs a value"),
            )),
            "sum_children" => {
                // Python `sum()` starts at int 0 and follows the numeric tower:
                // all-int children give an int; any float child promotes the
                // running total to float. `reduce_numeric` matches that.
                Maybe::Keep(reduce_numeric(&children, Num::Int(0), |a, b| a.add(b)))
            }
            "product_children" => {
                // Python's loop starts `result = 1` (int) and `*=` each child,
                // promoting to float on the first float child.
                Maybe::Keep(reduce_numeric(&children, Num::Int(1), |a, b| a.mul(b)))
            }
            "join_children" => {
                let sep = action.sep.as_deref().unwrap_or("");
                let joined = children
                    .iter()
                    .map(TransformValue::py_str)
                    .collect::<Vec<_>>()
                    .join(sep);
                Maybe::Keep(TransformValue::Str(joined))
            }
            "concat_children" => {
                let joined = children
                    .iter()
                    .map(TransformValue::py_str)
                    .collect::<Vec<_>>()
                    .concat();
                Maybe::Keep(TransformValue::Str(joined))
            }
            "first_child" => {
                Maybe::Keep(children.into_iter().next().unwrap_or(TransformValue::Null))
            }
            "wrap_list" => Maybe::Keep(TransformValue::List(children)),
            "wrap_dict" => {
                let key = action.key.clone().expect("wrap_dict needs a key");
                Maybe::Keep(TransformValue::Dict(vec![(
                    key,
                    TransformValue::List(children),
                )]))
            }
            "discard" => Maybe::Discard,
            other => panic!("unknown rule action: {other}"),
        }
    }

    /// Mirror of the generator's `_apply_token_action`.
    fn apply_token_action(action: &Action, tok: &Token) -> Maybe {
        let text = &tok.value;
        match action.kind.as_str() {
            "identity" => Maybe::Keep(TransformValue::Token {
                token_type: tok.type_.clone(),
                value: tok.value.clone(),
            }),
            "int_value" => Maybe::Keep(TransformValue::Int(
                text.parse::<i64>().expect("int_value: token is not an int"),
            )),
            "float_value" => Maybe::Keep(TransformValue::Float(
                text.parse::<f64>()
                    .expect("float_value: token is not a float"),
            )),
            "upper" => Maybe::Keep(TransformValue::Str(text.to_uppercase())),
            "lower" => Maybe::Keep(TransformValue::Str(text.to_lowercase())),
            "prefix" => {
                let prefix = action
                    .value
                    .as_ref()
                    .and_then(|v| v.as_str())
                    .expect("prefix needs a string value");
                Maybe::Keep(TransformValue::Str(format!("{prefix}{text}")))
            }
            "stringify" => Maybe::Keep(TransformValue::Str(text.clone())),
            "return_value" => Maybe::Keep(literal(
                action.value.as_ref().expect("return_value needs a value"),
            )),
            "discard" => Maybe::Discard,
            other => panic!("unknown token action: {other}"),
        }
    }

    /// A Python-numeric-tower scalar: an `int` that promotes to `float` the
    /// moment a float enters the computation, exactly as CPython's `+`/`*` do.
    #[derive(Clone, Copy)]
    enum Num {
        Int(i64),
        Float(f64),
    }

    impl Num {
        fn add(self, other: Num) -> Num {
            match (self, other) {
                (Num::Int(a), Num::Int(b)) => Num::Int(a + b),
                (a, b) => Num::Float(a.as_f64() + b.as_f64()),
            }
        }

        fn mul(self, other: Num) -> Num {
            match (self, other) {
                (Num::Int(a), Num::Int(b)) => Num::Int(a * b),
                (a, b) => Num::Float(a.as_f64() * b.as_f64()),
            }
        }

        fn as_f64(self) -> f64 {
            match self {
                Num::Int(i) => i as f64,
                Num::Float(f) => f,
            }
        }

        fn into_value(self) -> TransformValue {
            match self {
                Num::Int(i) => TransformValue::Int(i),
                Num::Float(f) => TransformValue::Float(f),
            }
        }
    }

    /// Fold the numeric children of a `sum_children` / `product_children` rule
    /// with `op`, starting from `init`, following Python's numeric tower. Panics
    /// on a non-numeric child, mirroring Python raising a `TypeError`.
    fn reduce_numeric(
        children: &[TransformValue],
        init: Num,
        op: impl Fn(Num, Num) -> Num,
    ) -> TransformValue {
        let mut acc = init;
        for c in children {
            acc = op(acc, expect_num(c));
        }
        acc.into_value()
    }

    fn expect_num(v: &TransformValue) -> Num {
        match v {
            TransformValue::Int(i) => Num::Int(*i),
            TransformValue::Float(f) => Num::Float(*f),
            other => panic!("expected a numeric child, got {other:?}"),
        }
    }

    /// Render a finite `f64` the way CPython's `str(float)` does for the common
    /// cases the action specs can produce: a whole-valued finite float keeps a
    /// trailing `.0` (`str(3.0) == "3.0"`), which Rust's `Display` drops. Other
    /// magnitudes use Rust's shortest round-tripping `Display`, which agrees with
    /// CPython's `repr` for ordinary decimals (the only floats the C1 specs reach
    /// via `float_value`). Exotic scientific-notation edge cases are out of scope
    /// for the committed fixtures.
    fn py_float_str(f: f64) -> String {
        if f.is_finite() && f == f.trunc() && f.abs() < 1e16 {
            format!("{f:.1}")
        } else {
            format!("{f}")
        }
    }
}

// ── Backend harness ──────────────────────────────────────────────────────────

use lark_rs::{Lark, LarkOptions, LexerType, ParserAlgorithm};
use transformer::PythonTransformerOracleBuilder;

/// Build a LALR parser for a fixture case under the given lexer, honoring the
/// `parser_options` the oracle was generated with (`keep_all_tokens`,
/// `maybe_placeholders`).
fn build_lark(case: &Value, lexer: LexerType) -> Result<Lark, String> {
    let grammar = case["grammar"].as_str().unwrap();
    let opts = case["parser_options"].as_object().unwrap();
    Lark::new(
        grammar,
        LarkOptions {
            parser: ParserAlgorithm::Lalr,
            lexer,
            start: vec!["start".to_string()],
            keep_all_tokens: opts
                .get("keep_all_tokens")
                .and_then(|v| v.as_bool())
                .unwrap_or(false),
            maybe_placeholders: opts
                .get("maybe_placeholders")
                .and_then(|v| v.as_bool())
                .unwrap_or(false),
            ..Default::default()
        },
    )
    .map_err(|e| format!("{e}"))
}

/// Run one fixture case under one (lexer) config and compare value + trace JSON
/// against the committed oracle. Returns `Ok(())` on full parity.
fn check_case_config(case: &Value, config_key: &str, lexer: LexerType) -> Result<(), String> {
    let cfg = &case["configs"][config_key];
    let status = cfg["status"].as_str().unwrap();
    // All C1 fixtures are status="ok"; if Python ever emits an error status for a
    // case the Rust side cannot meaningfully replay it, so skip (the schema test
    // already guards the error shape).
    if status != "ok" {
        return Ok(());
    }

    let lark = build_lark(case, lexer)?;
    let input = case["input"].as_str().unwrap();
    let tree = lark.parse(input).map_err(|e| format!("parse error: {e}"))?;

    let builder = PythonTransformerOracleBuilder::from_case(case);
    let (value, trace) = builder.transform(&tree);

    // Value parity.
    let got_value = value.to_json();
    let want_value = &cfg["value"];
    if &got_value != want_value {
        return Err(format!(
            "VALUE mismatch:\n  got:  {got_value}\n  want: {want_value}"
        ));
    }

    // Trace parity.
    let got_trace = Value::Array(trace.iter().map(transformer::TraceEntry::to_json).collect());
    let want_trace = &cfg["trace"];
    if &got_trace != want_trace {
        return Err(format!(
            "TRACE mismatch:\n  got:  {got_trace}\n  want: {want_trace}"
        ));
    }

    Ok(())
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[test]
fn test_transformer_oracle_schema_valid() {
    let data = load_transformer_cases();

    // Top-level structure.
    assert_is_object(&data, "root");
    let root = data.as_object().unwrap();

    assert!(
        root.contains_key("generator"),
        "root must have a 'generator' field"
    );
    assert_is_string(&root["generator"], "root.generator");

    assert!(
        root.contains_key("schema_version"),
        "root must have a 'schema_version' field"
    );
    assert_is_u64(&root["schema_version"], "root.schema_version");
    assert_eq!(
        root["schema_version"].as_u64().unwrap(),
        1,
        "expected schema_version 1"
    );

    assert!(root.contains_key("cases"), "root must have a 'cases' array");
    assert_is_array(&root["cases"], "root.cases");

    let cases = root["cases"].as_array().unwrap();
    assert!(!cases.is_empty(), "cases array must not be empty");

    // Validate each case.
    let mut names = std::collections::HashSet::new();
    for (i, case) in cases.iter().enumerate() {
        let cp = format!("cases[{i}]");
        assert_is_object(case, &cp);
        let obj = case.as_object().unwrap();

        // Required string fields.
        for field in ["name", "description", "grammar", "input"] {
            assert!(obj.contains_key(field), "{cp} must have a '{field}' field");
            assert_is_string(&obj[field], &format!("{cp}.{field}"));
        }

        // Name uniqueness.
        let name = obj["name"].as_str().unwrap();
        assert!(
            names.insert(name.to_string()),
            "{cp}: duplicate case name {name:?}"
        );

        // Action specs.
        for field in ["rule_actions", "token_actions"] {
            assert!(obj.contains_key(field), "{cp} must have a '{field}' field");
            assert_is_object(&obj[field], &format!("{cp}.{field}"));
            let actions = obj[field].as_object().unwrap();
            for (action_name, action_spec) in actions {
                validate_action_spec(action_spec, &format!("{cp}.{field}.{action_name}"));
            }
        }

        // Optional default handlers (null or action spec).
        for field in ["default_rule", "default_token"] {
            assert!(
                obj.contains_key(field),
                "{cp} must have a '{field}' field (null or action spec)"
            );
            if !obj[field].is_null() {
                validate_action_spec(&obj[field], &format!("{cp}.{field}"));
            }
        }

        // visit_tokens.
        assert!(
            obj.contains_key("visit_tokens"),
            "{cp} must have a 'visit_tokens' field"
        );
        assert_is_bool(&obj["visit_tokens"], &format!("{cp}.visit_tokens"));

        // parser_options.
        assert!(
            obj.contains_key("parser_options"),
            "{cp} must have a 'parser_options' field"
        );
        assert_is_object(&obj["parser_options"], &format!("{cp}.parser_options"));

        // configs: must have at least one, each is a config result.
        assert!(
            obj.contains_key("configs"),
            "{cp} must have a 'configs' field"
        );
        assert_is_object(&obj["configs"], &format!("{cp}.configs"));
        let configs = obj["configs"].as_object().unwrap();
        assert!(!configs.is_empty(), "{cp}.configs must not be empty");
        for (cfg_key, cfg_val) in configs {
            validate_config_result(cfg_val, &format!("{cp}.configs.{cfg_key}"));
        }
    }
}

#[test]
fn test_transformer_oracle_all_cases_ok() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let configs = case["configs"].as_object().unwrap();
        for (cfg_key, cfg_val) in configs {
            let status = cfg_val["status"].as_str().unwrap();
            assert_eq!(
                status, "ok",
                "case {name}:{cfg_key} has status {status:?}, expected 'ok'"
            );
        }
    }
}

#[test]
fn test_transformer_oracle_has_expected_configs() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();

    let expected_configs = ["lalr_basic", "lalr_contextual"];

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let configs = case["configs"].as_object().unwrap();
        for expected in &expected_configs {
            assert!(
                configs.contains_key(*expected),
                "case {name} is missing config {expected:?}"
            );
        }
    }
}

#[test]
fn test_transformer_oracle_traces_nonempty() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let configs = case["configs"].as_object().unwrap();
        for (cfg_key, cfg_val) in configs {
            if cfg_val["status"].as_str().unwrap() == "ok" {
                let trace = cfg_val["trace"].as_array().unwrap();
                assert!(
                    !trace.is_empty(),
                    "case {name}:{cfg_key} has an empty trace"
                );
            }
        }
    }
}

#[test]
fn test_transformer_oracle_has_required_coverage() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();
    let names: Vec<&str> = cases.iter().map(|c| c["name"].as_str().unwrap()).collect();

    // The issue requires all of these to be covered.
    let required = [
        "arithmetic_eval",
        "json_value_builder",
        "token_normalizer_upper",
        "alias",
        "transparent_rule",
        "expand1",
        "filtered_punctuation",
        "keep_all_tokens",
        "maybe_placeholders_true",
        "maybe_placeholders_false",
        "discard_token",
        "discard_rule",
        "default_rule_handler",
        "default_token_handler",
        "callback_order_trace",
    ];

    for req in &required {
        assert!(
            names.contains(req),
            "required case {req:?} is missing from the fixture"
        );
    }
}

#[test]
fn test_transformer_oracle_action_spec_language_neutral() {
    // Verify that action specs contain only JSON-primitive data — no Python
    // code, no lambda strings, no executable content.  This is the
    // "language-neutral" guarantee from the issue.
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();

    for case in cases {
        let name = case["name"].as_str().unwrap();
        for field in ["rule_actions", "token_actions"] {
            let actions = case[field].as_object().unwrap();
            for (action_name, action_spec) in actions {
                let obj = action_spec.as_object().unwrap();
                // Every key must be a string; every value must be a
                // JSON primitive (string, number, bool, null, array, object).
                // No "code", "lambda", "exec", "eval" keys allowed.
                let forbidden = ["code", "lambda", "exec", "eval", "python"];
                for key in obj.keys() {
                    assert!(
                        !forbidden.contains(&key.as_str()),
                        "case {name}.{field}.{action_name} has forbidden key {key:?} — \
                         action specs must be language-neutral"
                    );
                }
            }
        }
    }
}

// ── C3: value + trace parity over every C1 fixture ───────────────────────────

/// The C3 gate: for **every** fixture case, the Python-shaped backend must
/// reproduce both the Python value JSON and the Python trace, under LALR + basic
/// and LALR + contextual.
#[test]
fn test_transformer_backend_value_and_trace_parity() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();

    let configs = [
        ("lalr_basic", LexerType::Basic),
        ("lalr_contextual", LexerType::Contextual),
    ];

    let mut checked = 0usize;
    for case in cases {
        let name = case["name"].as_str().unwrap();
        for (config_key, lexer) in &configs {
            if let Err(e) = check_case_config(case, config_key, lexer.clone()) {
                panic!("case {name}:{config_key} failed parity:\n{e}");
            }
            checked += 1;
        }
    }
    assert!(checked > 0, "no fixture configs were checked");
}

/// Pin RFC §5: a kept terminal with **no** spec method must be materialized
/// silently (no trace entry), while a terminal *with* a method logs a visible
/// callback. `token_normalizer_upper` exercises both in one case: `NAME` has a
/// method (logged), `PUNCT` does not (kept silently as a Token value).
#[test]
fn test_engine_token_vs_visible_callback_distinction() {
    let data = load_transformer_cases();
    let cases = data["cases"].as_array().unwrap();
    let case = cases
        .iter()
        .find(|c| c["name"] == "token_normalizer_upper")
        .expect("token_normalizer_upper fixture present");

    let lark = build_lark(case, LexerType::Contextual).unwrap();
    let tree = lark.parse(case["input"].as_str().unwrap()).unwrap();
    let builder = PythonTransformerOracleBuilder::from_case(case);
    let (_value, trace) = builder.transform(&tree);

    // Only the NAME callbacks are visible; PUNCT is materialized silently.
    assert!(
        trace.iter().all(|t| t.name == "NAME" && t.kind == "token"),
        "expected only visible NAME token callbacks, got {trace:?}"
    );
    assert!(
        trace.iter().all(|t| t.name != "PUNCT"),
        "PUNCT has no spec method and must not produce a visible callback: {trace:?}"
    );
}
