//! Relative file-import oracle tests (Phase 3, issue #39).
//!
//! `%import .module (NAME, ...)` loads a sibling `.lark` file relative to the
//! importing grammar's directory, parses it through `load_grammar`, and copies the
//! requested terminals/rules (a rule pulls in its dependency closure, mangled under
//! the module name) — mirroring Python Lark's `GrammarLoader`.
//!
//! Oracle: `fixtures/oracles/imports/cases.json`, generated by
//! `tools/generate_oracles.py::generate_imports` via `Lark.open` so Python resolves
//! the same relative imports. The grammar files live under `tests/grammars/imports/`
//! (a subdirectory, so the oracle-coverage scan treats this single oracle as their
//! coverage rather than demanding one per fragment file).

mod common;

use common::{load_oracle, tree_matches_oracle};
use lark_rs::{Lark, LarkOptions, LexerType, ParserAlgorithm};
use std::path::{Path, PathBuf};

fn grammars_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/grammars")
}

/// Build a LALR parser from a grammar file, with relative file imports resolving
/// against that file's own directory (as Python Lark does for an opened grammar).
fn make_lalr_from_path(rel_path: &str) -> Lark {
    let path = grammars_dir().join(rel_path);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {e}", path.display()));
    let base = path.parent().map(Path::to_path_buf);
    Lark::new(
        &text,
        LarkOptions {
            parser: ParserAlgorithm::Lalr,
            lexer: LexerType::Contextual,
            start: vec!["start".to_string()],
            base_path: base,
            ..Default::default()
        },
    )
    .unwrap_or_else(|e| panic!("Grammar {rel_path} failed to load: {e}"))
}

#[test]
fn test_relative_imports_oracle() {
    let oracle = load_oracle("imports", "cases");
    let cases = oracle.as_array().expect("cases must be an array");

    let mut failures = Vec::new();
    for case in cases {
        let grammar = case["grammar"].as_str().expect("grammar field");
        let input = case["input"].as_str().unwrap_or("");
        let should_pass = case["should_pass"].as_bool().unwrap_or(false);
        let oracle_ok = case["ok"].as_bool().unwrap_or(false);

        let lark = make_lalr_from_path(grammar);
        let result = lark.parse(input);

        match (should_pass, oracle_ok, &result) {
            (true, true, Ok(tree)) => {
                if let Err(msg) = tree_matches_oracle(tree, &case["tree"]) {
                    failures.push(format!("{grammar} input={input:?}: tree mismatch: {msg}"));
                }
            }
            (true, true, Err(e)) => {
                failures.push(format!(
                    "{grammar} input={input:?}: expected parse success, got error: {e}"
                ));
            }
            (false, false, Err(_)) => {}
            (false, false, Ok(_)) => {
                failures.push(format!(
                    "{grammar} input={input:?}: expected parse failure, but parsing succeeded"
                ));
            }
            _ => failures.push(format!(
                "{grammar} input={input:?}: oracle/expectation disagree \
                 (should_pass={should_pass}, oracle_ok={oracle_ok})"
            )),
        }
    }

    assert!(
        failures.is_empty(),
        "relative file-import oracle failures ({}):\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// A file import with no base path (grammar built from a bare string) is
/// unresolvable — only the bundled `common` library is available — and must error
/// rather than silently drop the requested symbols.
#[test]
fn test_file_import_without_base_path_errors() {
    let res = Lark::new(
        "%import .tokens (NUMBER)\nstart: NUMBER\n",
        LarkOptions {
            parser: ParserAlgorithm::Lalr,
            lexer: LexerType::Contextual,
            start: vec!["start".to_string()],
            ..Default::default()
        },
    );
    assert!(res.is_err(), "expected ImportNotFound, got Ok");
}
